### ISSUE TITLE
v3文档有误

### ISSUE THREAD

**Issue by lqh-1997** [vuejs/docs-next-zh-cn#106]
https://github.com/vuejs/docs-next-zh-cn/blob/master/src/guide/migration/global-api.md#提供注入-provide--inject
在provide/inject处

```
app.provide({
  guide: 'Vue 3 Guide'
})
```

应为

```
app.provide('guide', 'Vue 3 Guide')
```

https://github.com/vuejs/docs-next/blob/master/src/guide/migration/global-api.md#provide--inject

**Comment by lqh-1997** [comment]
还有同一个地方的
```
export default {
  inject: {
    book: {
      from: guide
    }
  },
  template: `<div>{{ book }}</div>`
}
```
`guide` 应为 `'guide'`

**Comment by veaba** [comment]
#107  已修复该问题，现将 close 该 issue，感谢 @lqh-1997 的反馈。
