### ISSUE TITLE
v3文档翻译有误

### ISSUE THREAD

**Issue by Ryokutouto** [vuejs/docs-next-zh-cn#111]
[传入](https://v3.cn.vuejs.org/guide/teleport.html#%E4%B8%8E-vue-components-%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8)

![image](https://user-images.githubusercontent.com/44834187/93861008-63ad4e80-fcaf-11ea-9abb-77aa20a1b7dd.png)

原文: Let's take a look at modal-button.
翻译:为此，我们可以使用 Vue 的内置 <modal-button> 组件：

**Comment by veaba** [comment]
@Ryokutouto， 你好，感谢反馈，如果可以话，发起 PR 来参与修改该问题，这会更有意义。

**Comment by veaba** [comment]
该文档由 PR #139 修复，感谢你的反馈。现将 close 该 issue
