### ISSUE TITLE
[认领] [已翻译未校对] : src/guide/composition-api-provide-inject.md

### ISSUE THREAD

**Issue by GeekQiaQia** [vuejs/docs-next-zh-cn#136]
https://github.com/vuejs/docs-next-zh-cn/projects/3#card-44141841

**Comment by Jinjiang** [comment]
@veaba 确认一下这个部分的 review 是不是已经通过 #143 完成了? 如果已经完成了的话我觉得可以关掉这个 issue 了，同时 project board 上的状态也可以更新了。
谢谢

**Comment by veaba** [comment]
> @veaba 确认一下这个部分的 review 是不是已经通过 #143 完成了? 如果已经完成了的话我觉得可以关掉这个 issue 了，同时 project board 上的状态也可以更新了。
> 谢谢

我来操作即可。
