### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by justyeh** [vuejs/docs-next-zh-cn#164]
原始英文文档里描述关于v-if和v-for同时使用时，都说v-if现在比v-for有更高的优先级：

[v-if with v-for](https://github.com/vuejs/docs-next/blob/master/src/guide/conditional.md#v-if-with-v-for)

>v-if with v-for
>::: tip Note Using v-if and v-for together is not recommended. See the style guide for further information. :::  
>When v-if and v-for are both used on the same element, v-if will be evaluated first. See the list rendering guide for details.

[v-for with v-if](https://github.com/vuejs/docs-next/blob/master/src/guide/conditional.md#v-if-with-v-for)

>v-for with v-if
>:::tip Note that it's not recommended to use v-if and v-for together. Refer to style guide for details. :::  
>When they exist on the same node, v-if has a higher priority than v-for.

现中文文档这两处翻译错误  

[v-if-与-v-for-一起使用](https://v3.cn.vuejs.org/guide/conditional.html#v-if-%E4%B8%8E-v-for-%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8)

[v-for 与 v-if 一同使用](https://v3.cn.vuejs.org/guide/list.html#v-for-%E4%B8%8E-v-if-%E4%B8%80%E5%90%8C%E4%BD%BF%E7%94%A8)

**Comment by justyeh** [comment]
难道直接拷贝的v2文档?

**Comment by veaba** [comment]
有很大一部分都是迁移自 v2 ，如果你发现有不恰当之处，欢迎发起 PR 。

**Comment by veaba** [comment]
see #174，will be close the issue！ thank you!
