### ISSUE TITLE
参照原文，进行内容补充/删改：src/api/global-api.md

### ISSUE THREAD

**Issue by zhenzhenChange** [vuejs/docs-next-zh-cn#168]
# 内容补充与删改

## defineComponent

原文链接：https://v3.vuejs.org/api/global-api.html#definecomponent
补充内容：参数可以是一个 `setup` 函数，并翻译注释

---

以下两个删改根据原文仓库的 [PR](https://github.com/vuejs/docs-next/pull/523)

## defineAsyncComponent

原文链接：https://v3.vuejs.org/api/global-api.html#defineasynccomponent
删除内容：删除 `retryWhen` 和 `maxRetries` 选项
补充内容：添加 `onError` 钩子选项，并翻译注释

## resolveComponent

原文链接：https://v3.vuejs.org/api/global-api.html#resolvecomponent
修改内容：参数描述由 `component` 修改为 `name`

---

如有不妥之处，敬请指正~ (#^.^#)

**Comment by zhenzhenChange** [comment]
已提 PR #169

**Comment by veaba** [comment]
The relevant PR has been merged.
