### ISSUE TITLE
翻译错误：[foces]=>[focus]

### ISSUE THREAD

**Issue by kinvirgo** [vuejs/docs-next-zh-cn#171]
文档错误

原文：
In this example, when eventName's value is "focus", v-on:[eventName] will be equivalent to v-on:focus

中文错误：[地址→](https://vue3js.cn/docs/zh/guide/template-syntax.html#%E5%8A%A8%E6%80%81%E5%8F%82%E6%95%B0)
在这个示例中，当 eventName 的值为 "focus" 时，v-on:[eventName] 将等价于 v-on:**foces**

**Comment by veaba** [comment]
该网站非 Vuejs 官方维护，官方文档未发现该问题，现将 close 该 issue。
