### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by goldingking** [vuejs/docs-next-zh-cn#172]
https://vue3js.cn/docs/zh/guide/migration/global-api.html#%E4%B8%80%E4%B8%AA%E6%96%B0%E7%9A%84%E5%85%A8%E5%B1%80-api-createapp
中的一句话：
全局配置使得在同一页面上的多个“app”之间共享同一个 Vue 副本非常困难，**但全局配置不同**
加粗部分应该不是要讲全局配置，我猜测应该是说全局API

**Comment by zhenzhenChange** [comment]
这个好像是民间的文档 O(∩_∩)O哈哈~

**Comment by veaba** [comment]
请参考[原文](https://github.com/vuejs/docs-next/blob/d7b4cc8c370a607d54423ce65e9d6f597a4763b2/src/guide/migration/global-api.md#L44)。

如认为情景上下文有问题，可以考虑给 [英文仓库](https://github.com/vuejs/docs-next) 发起 PR 来修复该问题，再重新打开该 issue 讨论。

目前该 issue 无需继续展开讨论，现将 close 该 issue。
