### ISSUE TITLE
集中翻译和校对工作汇总

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/docs-next-zh-cn#18]
大家好，目前 Vue 3.0 的中文文档站处在刚刚起步的状态，有大量的文档有待集中翻译和校对，也希望可以得到社区的大力支持！

所以我们创建了这个 issue 来汇总这些工作。

**首先介绍一下目前文档站的状态：**

1. 我们按照页面为颗粒度将所有需要翻译和校对的页面统计在了 GitHub project board：https://github.com/vuejs/docs-next-zh-cn/projects/3
2. 每个页面理论上都需要经历“未翻译”、“正在翻译”、“已翻译未校对”、“已完成”四个状态。

**如何参与本次集中翻译和校对**

目前的页面有两类状态，一类是英文版，尚未翻译，另一类是已经翻译但是并未有其他人校对。

- 对于尚未翻译的内容
  1. 创建一则新的 issue 认领翻译，我们看到之后会整理到 project board (移动到"正在翻译"，并注明认领人)
  2. 翻译完毕后，提交并创建 PR，我们看到之后整理到 project board (移动到"已翻译待校对")
  3. 超过社区 2 人或有 Vue 团队成员校对并 approve 之后，我们合并分支并整理到 project board (移动到"已完成")
  4. 该 issue 关闭

- 对于已经翻译但尚未校对的内容
  1. 创建一则新的 issue 认领校对，我们看到之后会整理到 project board (移动到“已翻译待校对”，并注明认领人)
  2. 校对完毕后，提交修改意见并创建 PR
  3. Vue 团队成员进行校对和合并分支，并整理到 project board (移动到已完成)
  4. 该 issue 关闭

注意可以重复校对，但我们会尽量回避大家重复翻译和过度集中校对某一篇文档，所以建议大家参与之前来这里认领一下以避免其他人重复翻译或过度校对。

**翻译相关的注意事项**

详见 [wiki](https://github.com/vuejs/docs-next-zh-cn/wiki)

_如果大家有兴趣参与翻译和校对，欢迎创建 issue 认领相关工作！_

谢谢

**Comment by zhaozhe0831** [comment]
我可以校对一下，翻译水平感觉不太行...
我之前翻译了几个迁移策略的部分，照着谷歌有道翻译的。
[掘金个人主页](https://juejin.im/user/2770425031695415/posts)

**Comment by Jinjiang** [comment]
@zhaozhe0831 谢谢你的建议。如果你有更好的翻译建议欢迎发 PR 校对或讨论，通过积极的方式贡献到这里，没有必要指责其他人的工作🙏

**Comment by zhaozhe0831** [comment]
> @zhaozhe0831 谢谢你的建议。如果你有更好的翻译建议欢迎发 PR 校对或讨论，通过积极的方式贡献到这里，没有必要指责其他人的工作🙏
> 
> Btw 我们的翻译和校对工作会做到大家满意为止，不回避任何问题，并且会长期保持更新和改进，请大家放心

我的意思是我的翻译水平不太行，所以只能校对了。。。

**Comment by Justineo** [comment]
我建议大家可以试一下 [DeepL](https://www.deepl.com/translator)，翻译效果个人认为比谷歌翻译好。

**Comment by Jinjiang** [comment]
目前所有已知的文档都已经翻译完毕，接下来的工作基本上都以校对为主了。欢迎大家继续帮忙校对。具体进度见 https://github.com/vuejs/docs-next-zh-cn/projects/3

**Comment by zhenzhenChange** [comment]
> 目前所有已知的文档都已经翻译完毕，接下来的工作基本上都以校对为主了。欢迎大家继续帮忙校对。具体进度见 https://github.com/vuejs/docs-next-zh-cn/projects/3

英文原文有些地方新增了一些内容（比如全局API部分），是到时候合并过来呢，还是手动加上呢

**Comment by Jinjiang** [comment]
> 英文原文有些地方新增或修改了一些内容（比如全局API部分），是到时候合并过来呢，还是在这个仓库里自己手动加上呢

可以参考 [wiki](https://github.com/vuejs/docs-next-zh-cn/wiki/%E5%8D%8F%E4%BD%9C%E6%8C%87%E5%8D%97#32-%E9%99%A4%E4%BA%86%E7%BF%BB%E8%AF%91%E5%92%8C%E6%A0%A1%E5%AF%B9)：“定期同步最新的翻译：颗粒度 (所以更新、某个页面或某个细节) 可以自选，可以直接发起 PR”。和这里的集中翻译和校对工作是分开考虑的。欢迎大家帮助我们更新，我们同时会定期同步，确保不会错过任何英文版的更新。

**Comment by Alfxjx** [comment]
你好 我想参与校对工作，请问是在project里面找到已翻译未校对的issue,然后另外发issue认领校对嘛

**Comment by Jinjiang** [comment]
@Alfxjx 是的，可以参考已有的认领翻译或校对的 issue，谢谢

**Comment by sdrkyj** [comment]
哇，刚看见这个翻译页，然而内容都已经翻译完了。不过有的官网页面还是英文。

**Comment by Jinjiang** [comment]
Hi 这里跟诸位汇报一下我们目前翻译的整体进度：

截止到昨天 (2021年6月3日)
1. 绝大部分的文档都已经翻译并至少一人次的校对
2. 其余未达到这一状态的页面也均被人认领
    - `src/guide/transitions-state.md` #113 PR #181
    - `src/guide/transitions-list.md` #115 @mcdongWang
    - `src/guide/contributing/doc-style-guide.md` #329 @KarthusLorin
    - `src/guide/migration/render-function-api.md` #398 @lumicia
    - `src/api/application-config.md` #372 @Aaronlamz
    - `src/api/special-attributes.md` #540 @ShroXd
    - `src/api/options-assets.md` #532 @watonyweng
3. 在和英文版同步的过程中产生了一些新页面待翻译
    - `src/guide/ssr/build-config.md`
    - `src/guide/ssr/getting-started.md`
    - `src/guide/ssr/hydration.md`
    - `src/guide/ssr/introduction.md`
    - `src/guide/ssr/routing.md`
    - `src/guide/ssr/server.md`
    - `src/guide/ssr/structure.md`
    - `src/guide/ssr/universal.md`
    - `src/guide/migration/suspense.md`
    - `src/guide/migration/vnode-lifecycle-events.md`
    - `src/guide/migration/mount-changes.md`
    - `src/guide/migration/props-data.md`
    - `src/guide/migration/emits-option.md`

详情请参见我们的 GitHub Project 页面：https://github.com/vuejs/docs-next-zh-cn/projects/3

在这里由衷感谢每一位译者的贡献！同时也号召一下已经认领校对的几位同学再加把劲：）
关于新产生的待翻译的页面，也鼓励更多的人来认领，参与翻译和校对的工作！

由于再往后可预见的翻译和校对的工作不会大量集中出现，所以我们待这些工作均有人认领之后，上述 GitHub Project 页面会逐步弃用并关闭，而转为在 issue list 上直接展开同步和翻译的相关讨论。感谢大家的理解。

**Comment by veaba** [comment]
现阶段所追踪的所有 project 任务已 100% review 完成，撒花。
![image](https://user-images.githubusercontent.com/8652596/124374316-cadf4100-dccc-11eb-8e75-f007e6add5b4.png)

再次感谢每一位译者的贡献！

/cc @Jinjiang @Justineo

**Comment by Jinjiang** [comment]
不好意思占用这里跟大家分享一些接下来的计划：

接下来我们会定期从英文原版同步最新的文档更新，大家可以通过这个 issue filter 了解到所有的同步行动：
https://github.com/vuejs/docs-next-zh-cn/pulls?q=is%3Apr+label%3A%E4%BB%8E%E8%8B%B1%E6%96%87%E7%89%88%E5%90%8C%E6%AD%A5+is%3Aclosed

在每次同步的过程中，我们会先保证内容的同步性，比如把最新的段落或页面复制到这里，关于一些比较大段的英文内容，鉴于这些翻译本身可能需要更多的时间完成翻译或需要必要的讨论，我们会就近临时加上 `<!-- TODO: translation -->` 这样的代码注释。这样做同步完成之后：1) 如果大家在阅读文档的时候发现了英文的部分，或 2) 在源码中发现了这样的注释，那么非常欢迎大家帮忙完成翻译。
另一个比较方便的找到这些代码注释的方式是通过这个链接：
https://github.com/vuejs/docs-next-zh-cn/search?q=TODO%3A+translation

上述内容我同时也会更新到仓库的 README。

谢谢大家
