### ISSUE TITLE
生命周期图片被压缩了

### ISSUE THREAD

**Issue by php4world** [vuejs/docs-next-zh-cn#183]
[文档链接](https://v3.cn.vuejs.org/guide/instance.html#生命周期图示)
![image](https://user-images.githubusercontent.com/24400760/95694485-e305c080-0c64-11eb-961d-58ecdb6d9e76.png)

**Comment by Otto-J** [comment]
比对了一下两边文档引用的图片 base64 是一致的 ：uQmCC，是同一张图，没有被压缩。

看截图感觉是渐进式图片，还没加载完？

**Comment by php4world** [comment]
是我浏览器的问题。强刷已解决。不知道为什么没有加载完就被缓存了
