### ISSUE TITLE
搜索功能和英文站不一致

### ISSUE THREAD

**Issue by huzhengen** [vuejs/docs-next-zh-cn#186]
比如搜索“toRefs”

英文站能直接搜索到 API，中文站不能

中文站搜索截图：

![vue3-cn](https://user-images.githubusercontent.com/10569262/95718390-f6368180-0ca0-11eb-89cc-4db8cbdc15b9.png)

英文站搜索截图：

![vue3-en](https://user-images.githubusercontent.com/10569262/95718416-ffbfe980-0ca0-11eb-8f6c-e084ce8788fc.png)

**Comment by veaba** [comment]
@Jinjiang 麻烦协调这一块，不出意外的话，应该要保持中英文的配置要一致，下面我列出来两个版本的地址：:pray:

- [英文版：vuejs-v3.json](https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs-v3.json)
- [中文版v3：vuejs-cn3.json](https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs_cn3.json)

另外，这个功能好像不是特别稳定，我现在在 中文 和 英文 站都没看到它了。

![image](https://user-images.githubusercontent.com/8652596/95816658-2f7afa00-0d52-11eb-95f6-9a3cfce261cc.png)

![image](https://user-images.githubusercontent.com/8652596/95816856-ad3f0580-0d52-11eb-8916-562e53c05971.png)

有这样的一个错误，应该也是网络问题引起，后续我持续关注下：
![image](https://user-images.githubusercontent.com/8652596/95817304-afee2a80-0d53-11eb-8df9-648b501a50cd.png)

**Comment by Jinjiang** [comment]
![image](https://user-images.githubusercontent.com/206848/97130466-82a27300-177c-11eb-8723-c84e55e4cc99.png)

![image](https://user-images.githubusercontent.com/206848/97130481-89c98100-177c-11eb-9565-93396b7b1228.png)

搜索规则更新了，现在应该行为一致了

将来如果发现新的搜索问题可以另外再开 issue

谢谢
