### ISSUE TITLE
点击文档/生态系统等后，鼠标离开选择框没有消失

### ISSUE THREAD

**Issue by tangyouge** [vuejs/docs-next-zh-cn#196]
如题，点击文档/生态系统/支持 Vue/多语言后，出现选择框，但是再点击的时候，选择框不消失。目前应该是 hover 事件是正常的，click 有问题。

**Comment by Jinjiang** [comment]
经过测试我发现英文版也有同样的问题，建议直接反馈给英文版仓库或 vuepress 仓库。

**Comment by Jinjiang** [comment]
该 issue 已经反馈到了主仓库。今后会随主仓库同步更新。谢谢

**Comment by Jinjiang** [comment]
Hi all，由于此 issue 可能会变成一个长期的 vuepress 的问题进行追踪，由于我们本身有定期从英文站同步更新的机制，且我们自身不产生额外的 action，个人感觉这里可能没有特别大的另行的意义了，在此我们打算关闭这个 issue。如果未来 vuepress 有相应的更新，进而英文站做了同步，我们中文站会借定期从英文站同步的机会将其同步过来。感谢诸位的理解。
