### ISSUE TITLE
认领已翻译未校对：【校对】：src/guide/reactivity.md

### ISSUE THREAD

**Issue by heart-er** [vuejs/docs-next-zh-cn#20]
拉了分支，帮忙校对高级指南里的响应式、组合API 部分

**Comment by heart-er** [comment]
响应式部分链接: https://github.com/vuejs/docs-next-zh-cn/pull/22/commits/f65ff3e8baeb2128b408ba12c34c32c8824061ce

**Comment by zhaozhe0831** [comment]
现在这是尚未校对吧，我要是想校对的话，需要自己建立另外一个issue吗？

**Comment by Jinjiang** [comment]
Hi @zhaozhe0831 在这里留言应该就可以了，另外创建 issue 也行。我们会在 project board 做记录。谢谢
