### ISSUE TITLE
【认领】【翻译】/src/coc/index.md

### ISSUE THREAD

**Issue by xingorg1** [vuejs/docs-next-zh-cn#210]
【认领】【翻译】/src/coc/index.md

**Comment by veaba** [comment]
@xingorg1 coc 部分不属于开放计划中的内容，我们实际上不是很赞同对此部分翻译。建议你对 project 中 **已翻译待校对** 部分做 review。

@Jinjiang @Justineo 你们怎么看，此前有关于 [coc 部分的讨论（链接受限访问）](https://github.com/orgs/vuejs/teams/docs-cn/discussions/4) 。

**Comment by xingorg1** [comment]
好的，那我就去做review吧。不太懂规则，造成打扰实在抱歉

**Comment by Jinjiang** [comment]
坦白说我觉得 coc 不在我们一定要翻译的范围里。所以我们先专注在和 Vue 直接相关的文档内容上吧。
coc 可以到项目处在稳定的维护期之后再酌情考虑，目前我们可以先把这个部分放一放。
谢谢
