### ISSUE TITLE
文档没有搜索了，很不方便啊...

### ISSUE THREAD

**Issue by wjw-gavin** [vuejs/docs-next-zh-cn#212]
之前还有的，现在没有了。。。

**Comment by veaba** [comment]
@Jinjiang @Justineo 网络不稳定，是不是可以考虑移除 algolia 特性？#186

**Comment by Jinjiang** [comment]
我这边是可以正常访问的。
@Justineo 能帮忙看看是什么情况吗？或者任何人方便的话可以提供更多信息，比如截图或动图之类的。

另外 algolia 的问题我已经在联系他们在看了。

**Comment by veaba** [comment]
@Jinjiang GIF
![Desktop 2020 10 24 - 14 16 54 02 00_00_11--00_00_31](https://user-images.githubusercontent.com/8652596/97069635-1dc40d00-1604-11eb-9d98-9380d09e4085.gif)

**Comment by Jinjiang** [comment]
感觉这个问题我这边能做的比较有限，根据我的推断，首先：

1. 绝大多数内容可以正常打开，说明 v3.cn.vuejs.org 本身的访问速度和稳定性是有保障的
2. 部分功能存在问题或响应慢，有可能是一些来自三方域名的资源或请求被阻塞了
3. DocSearch 本身的服务在国内很多开源项目都有运用，所以本身的服务在国内应该是足够快速和稳定的

所以我优先排查一下所有来自三方域名的资源。

![image](https://user-images.githubusercontent.com/206848/97098897-380df180-16bd-11eb-9d47-480ffd04601c.png)

这是我自己电脑里所有网络请求根据域名排序的结果，应该全部的三方资源都在这里了。但是我这边的访问速度不太具有参考意义，所以得有劳 @veaba @Justineo 二位和更多其他用户继续排查跟进了 🙏

谢谢

**Comment by veaba** [comment]
发一下我这边的调试结果：
1. 在chrome 下，容易出现 `Uncaught SyntaxError: Unexpected end of input` 错误，但在firefox ，以及 edge 下，搜索功能延迟8s 左右下是会出来的。
2. docsearch 的库，在静态资源下是调用本地的js文件，并非第三方，可以在gh-pagas 分支中看到 类似 `vendors~docsearch.3f439199.js` 的文件
3. vue 3 英文站和中文站表现也是一致，最近搜索功能丢失的情况更加频繁。
4. 在localhost 下 是秒出来docsearch 功能
5. 所以我的排查结果转向 ：
  - Chrome 的网络机制差异
  - docsearch 本身 对 document 的挂载
  - cloudflare 对 js 文件的拦截
6. 随后，我在国内服务器部署了站点，访问各方面都是正常。

![image](https://user-images.githubusercontent.com/8652596/97101832-8205d000-16db-11eb-8236-a0c0c320d687.png)

所以，可能的问题是，cloudflare 拦截了 docsearch！（对比图发现丢失了3个 js文件）

![image](https://user-images.githubusercontent.com/8652596/97101841-a9f53380-16db-11eb-88e1-8cdc01e7adda.png)

即：`153.xxx.js`、`10.82b400e4.js`、`vendors~docsearch.xxx.js` ，分别对应：serviceWorker、URLSearchParams、docsearch 功能。

解决办法：我觉得应该是处理下 cloudflare 控制台的访问限制情况。

**Comment by veaba** [comment]
这会，又出来了，基本时好时坏。

![image](https://user-images.githubusercontent.com/8652596/97101980-91394d80-16dc-11eb-95ea-1d10eac3c84c.png)

**Comment by veaba** [comment]
Hi，近半年来追踪和观察，目前无法搜索的问题已基本消失。
现在，将 close 该 issue，如有后续问题，再重新打开。
