### ISSUE TITLE
[翻译讨论] src/guide/installation.md

### ISSUE THREAD

**Issue by xingorg1** [vuejs/docs-next-zh-cn#214]
原文：Vue.js is built by design to be incrementally adoptable。
译文：Vue.js 在设计上是可以逐步采纳的。

感觉这里“is built by”没翻译出来啊是不是~

**Comment by veaba** [comment]
英文版本 有所更新，中文版未能跟进，现在对应更新就好了。

**Comment by veaba** [comment]
另外，这个 章节 已有 PR，建议另选。#207

**Comment by Jinjiang** [comment]
感觉和 #205 更相关
