### ISSUE TITLE
几个名词的译法讨论

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/docs-next-zh-cn#217]
- Composition API：部分地方译为“组合 API”。之前翻译 Composition API RFC 的时候已经约定为了“组合式 API”
- Options API：部分地方译为“选项 API”。同上，约定为了“选项式 API”
- BREAKING：“非兼容”，多出现在 `migration/*` 的页面
- Reactivity：“响应性”
- Teleport：经过和小右确认，保留“Teleport”的英文名词
- Assets：“资源”，例如 directives、components 都属于资源
- API Reference：“API 参考”

上述内容可能需要集中批量处理一下

另外还有一个需要批量处理的地方是部分标题文字经过翻译之后可能会出现其它地方的锚点仍保留了英文导致锚点失效的问题。这里需要集中 review 一下

**Comment by veaba** [comment]
我在一楼里面再补充，~reactive~。 来源[术语翻译约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A)

**Comment by Jinjiang** [comment]
Assets 印象中之前也是一直这么翻译的，如果有更好的译法我们再随时替换掉吧，你看如何

**Comment by Jinjiang** [comment]
provide 和 inject 我觉得也可以不翻译，另外这两个都是动词，似乎也不太会独立出现，印象中它们出现的场景都是特指 Vue 的 API，所以应该没问题。

/cc @Justineo

**Comment by Jinjiang** [comment]
Btw 更多词汇的翻译讨论我们另外开新的 issue 吧，这样颗粒度比较好控制

**Comment by veaba** [comment]
@Jinjiang @Justineo 那现在对 `provide/inject` 以及 `Proxy/proxy` 的译法共识基本就是：
保持原文，不改动大小写（原文对大小写的使用用途基本保证了其用于 `特殊用法` 还是 `日常表达`，无需处理）。

**Comment by veaba** [comment]
更新：`provide/inject` 将在下一个同步原仓库后改动。
