### ISSUE TITLE
部分 property 推荐进行翻译

### ISSUE THREAD

**Issue by heart-er** [vuejs/docs-next-zh-cn#23]
![image](https://user-images.githubusercontent.com/24717511/92438340-348cdc80-f1db-11ea-99c6-7240b2ffa7da.png)
比如该图片里的内容，ref对象只包含一个名为value的property，这个地方，翻译为 ref对象只包含一个名为value的属性 会不会更加贴切一点

**Comment by veaba** [comment]
目前是沿用 v2 的语法， 对于 `attribute` 与 `property` 都保持了原英文叫法。
