### ISSUE TITLE
如题： 跨项目引用组件 ，组件嵌套层级达到二级及以上，会出现以下警告，并无法显示组件内容（附赠问题文件）

### ISSUE THREAD

**Issue by asd123a20** [vuejs/docs-next-zh-cn#238]
resolveComponent can only be used in render() or setup().
Invalid VNode type: Symbol(Text) (symbol) 

https://github.com/asd123a20/admin.git

**Comment by Justineo** [comment]
您好，这里不接受关于使用问题的 issue，请[给主仓库提交 issue](https://new-issue.vuejs.org/?repo=vuejs/vue-next&lang=zh-cn)。

Ps. 请提供最小化的复现。
