### ISSUE TITLE
认领已翻译未校对：【校对】：src/guide/reactivity-fundamentals.md 校对

### ISSUE THREAD

**Issue by heart-er** [vuejs/docs-next-zh-cn#24]
帮忙校对高级指南里的响应式原理部分

**Comment by heart-er** [comment]
校对内容链接：https://github.com/vuejs/docs-next-zh-cn/pull/22/commits/529c046d146e7028bb2b43a8dcfb38bca998c6e1

**Comment by veaba** [comment]
@heart-er  该 issue 关联的 PR #22 ，有新的更新动作，请关注  PR #22
