### ISSUE TITLE
「 不成熟的小建议 」关于 Vue.js 文档的 Codepen 代码示例汉化

### ISSUE THREAD

**Issue by ShenQingchuan** [vuejs/docs-next-zh-cn#248]
其实在 Vue 2 的文档中已经有了不少的代码示例，他们几乎很少有改动，需要更新、同步的频率很低（虽然这也很可能导致某一个变动不易察觉），但可能原先涉及到的机制并不算特别重要、又或许这些动画并不太影响阅读体验，中文文档并未对其进行汉化。

但 vue-docs-next 大量使用了 codepen 来作为代码示例，而其内容实质上也是文档很重要的一部分。
活灵活现的例子可能比大段大段的文字更容易吸引初学者。
Vue 官方文档团队在代码示例的动画上做的也很用心。

我这里自己有一些尝试，但因个人事务繁忙没有后续维护，想建议中文文档团队翻译一下 codepen 里的一些提示文字
若要参见我的示例可以看我自己维护的一个文档版本里的 demo：[https://vue.techdict.pro/guide/optimizations.html#virtual-dom](https://vue.techdict.pro/guide/optimizations.html#virtual-dom)
可能需要中文文档官方维护一个 codepen 的仓库，保存所有的 demo : [https://codepen.io/collection/nRqqNz](https://codepen.io/collection/nRqqNz)

**Comment by veaba** [comment]
虽然看上去挺吸引人的，尽管几乎很少改动，但无疑增加了社区维护的成本。

你们怎么看？ @Jinjiang   @Justineo

**Comment by Jinjiang** [comment]
我建议等全部正文校对完成之后再考虑要不要做，而且 Codepen 代码的翻译和定期同步不像 GitHub 这么方便，所以感觉必要性不大且比较费事，看到时候大家的精力如何吧。
另外也可以参考一下其他语言的翻译，比如日语版本是否有做翻译，有没有什么维护技巧之类的。

**Comment by wxsms** [comment]
> 他们几乎很少有改动，需要更新、同步的频率很低（虽然这也很可能导致某一个变动不易察觉）

个人认为，文档在不同语言之间的一致性是很重要的。过时的代码示例对阅读者来说无疑是一个巨大的坑。

**Comment by Jinjiang** [comment]
#886
