### ISSUE TITLE
关于应用配置api问题

### ISSUE THREAD

**Issue by daimashangchuan** [vuejs/docs-next-zh-cn#257]
@vue/cli搭建
mian.ts中
const app = createApp(App);
api app.config.globalProperties.foo = 'bar' 
app.mount('#app');
在组件中使用
 mounted() {
    console.log("this.foo:===", this.foo);
 },
编辑器飘红     浏览器报错   但是可以正常打印出来

**Comment by veaba** [comment]
该 issus 范畴不属于文档相关，请移步到其他社区咨询，现 close 该 issue。
