### ISSUE TITLE
更新 /src/guide/installation.md 部分措辞

### ISSUE THREAD

**Issue by zhenzhenChange** [vuejs/docs-next-zh-cn#261]
- `package` -> `包`
- `发布` 与 `发行` 统一为其中一个应该更合适
- `WIP` = `Work In Process` 应该可以直译吧？
- `Extension` -> `扩展程序`
- `开发` 单文件组件 -> `编写` 单文件组件（用开发，感觉是在维护单文件组件这个功能的意思）
- `batteries-included` -> `功能齐备` （前面一个倒是翻译了）
  - 查了一下还有人提问过 https://www.zhihu.com/question/24710451
- Vite 的介绍沿用了 Vite 仓库的 README
- `pre-minified` -> `预先压缩过的`

其他修改的话有些是根据原文补充，有些是列表格式，以及一些代码格式。

另外  in-DOM HTML 应该如何翻译呢？

**Comment by zhenzhenChange** [comment]
好像有些 issue 和 pr 的格式不太对，勿怪嘻嘻~

**Comment by veaba** [comment]
`in-DOM HTML`  译为——“内嵌式 HTML” ？
@Justineo

**Comment by veaba** [comment]
related #262

**Comment by Justineo** [comment]
我觉得 in-DOM 挺难准确翻译的，内嵌式 HTML 也没有表达嵌入哪里。

我看之前“in-DOM template”都翻译成“in-DOM 模板”了，这里要不先保持一致？

**Comment by veaba** [comment]
> 我觉得 in-DOM 挺难准确翻译的，内嵌式 HTML �也没有表达嵌入哪里。
> 
> 我看之前“in-DOM template”都翻译成“in-DOM 模板”了，这里要不先保持一致？

Long time no see. 看起来和我一样去度假了~~  🤪 

`in-DOM` 我记得我好像译为 `DOM中/内`了。不过，既然可以存在含糊不清的译法，可以先保留原译。

以前的译法，我后面找个时间再改回来原英文。

**Comment by Justineo** [comment]
> Long time no see. 看起来和我一样去度假了~~ 🤪

并没有，近期事情比较多……

**Comment by Justineo** [comment]
已合入。

**Comment by veaba** [comment]
@zhenzhenChange 后续译法可以单独发起 issue 来单独讨论，这个 issue 关联 PR 已被关闭，后续将关闭此 PR。

以下为个人看法：
1、`WIP` 应该认为一个专门的术语，我个人认为最好保持原文。
2、`batteries-included` —— 译为 `功能齐备` 应该是恰当的。

🎉

**Comment by Justineo** [comment]
> 1、`WIP` 应该认为一个专门的术语，我个人认为最好保持原文。

WIP 这个缩写大多数人是看不懂的，我理解最好翻译一下。

**Comment by zhenzhenChange** [comment]
> > 1、`WIP` 应该认为一个专门的术语，我个人认为最好保持原文。
> 
> WIP 这个缩写大多数人是看不懂的，我理解最好翻译一下。

对对对，我一开始看到 WIP 是真的不知道是啥意思，还是去百度的。当然，对于专业的开发者来说，这个词是专业词汇的缩写，这是他们之间的一种共识。但是对于普通的开发者，阅读文档的时候着实可能会感到疑惑。或者可以这样 `WIP（正在进行中）`，保持原文但补上中文，这也能让看到的人能够理解这个词。

**Comment by veaba** [comment]
咳，我一开始也是不懂，也是要查一下。:smile: 

@zhenzhenChange 统一楼上说法。

在尊重专门术语的情况下，又给出译法，下次用户看到了，也能够学习个新词。

`WIP` —— `WIP (进行中)` 。

印象中，我记得在文档中就出现过一次这个词，译的话会更好，如果多次可能就考虑下保留，为此列出我对这个译法的偏好程度：

1. `WIP` —— `WIP (进行中)`    打个 10 分
2. `WIP` —— `进行中`              打个 8 分
3. `WIP` 不变                            打个 5 分

**Comment by Justineo** [comment]
也可以这样：

进行中 (WIP, Work in Progress)

**Comment by zhenzhenChange** [comment]
nice

**Comment by veaba** [comment]
*

> 也可以这样：
> 
> 进行中 (WIP, Work in Progress)

这个译法更好。
