### ISSUE TITLE
[认领&名词相关] [已翻译未校对] : src/guide/migration/fragments.md

### ISSUE THREAD

**Issue by amzrk2** [vuejs/docs-next-zh-cn#276]
https://github.com/vuejs/docs-next-zh-cn/projects/3#card-44141690

原文：https://v3.vuejs.org/guide/migration/fragments.html#overview
虽然不是很重要的概念，fragments 目前被翻译为 "片段"，术语翻译约定中没有找到相关的内容，是否保留这个译法？

**Comment by veaba** [comment]
仅当存在歧义且讨论过后才会被写入到约定 wiki 中。

`fragments`  目前看来，可以沿用此前的译法。
