### ISSUE TITLE
示例代码是否有问题？

### ISSUE THREAD

**Issue by qixiaobro** [vuejs/docs-next-zh-cn#282]
在[响应式计算和侦听](https://v3.cn.vuejs.org/guide/reactivity-computed-watchers.html#%E8%AE%A1%E7%AE%97%E5%80%BC)一节
示例代码：
```js
const count = ref(1)
const plusOne = computed(() => count.value++)

console.log(plusOne.value) // 2

plusOne.value++ // error
```
这个输出的 2 好像并不正确。 输出的是 1。

只有
```js
const plusOne = computed(() => count.value + 1)

console.log(plusOne.value) // 输出的 才是 2.
```

不知是bug还是我自己的demo有问题。

**Comment by qixiaobro** [comment]
补充：
在英文文档中 示例代码是下面的
![截屏2020-11-26 上午12 10 42](https://user-images.githubusercontent.com/34623348/100253361-f8684d00-2f7b-11eb-9938-0b64bb6d3a6a.png)

**Comment by veaba** [comment]
更新未及时所致，见 [commit](https://github.com/vuejs/docs-next/commit/fcc21b1735c6e59b1bab1e395e70013d2771e83b#diff-89664ba2a61a56095e5fec5ed2bc4fa5be629e0beda5bc25262d76b9cbcbe1eb)

**Comment by veaba** [comment]
related #283， 该问题修复已合并到 master
