### ISSUE TITLE
同步: eb1964c - fa461e8

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#285]
## 定期大面积同步英文仓库

本次同步范围：[eb1964c —— fa461e8](https://github.com/vuejs/docs-next/compare/eb1964c...fa461e8)

本次更新涵盖以下内容：
- 移除多余空格
- 新增若干文件(待翻译，已添加 project 进度中，未开始)
  - src/guide/migration/attrs-includes-class-style.md
  - src/guide/migration/children.md
  - src/guide/migration/emits-option.md
  - src/guide/migration/listeners-removed.md
  - src/guide/migration/transition-group.md
  - src/guide/migration/v-on-native-modifier-removed.md
  - src/guide/tooling/deployment.md
  - src/search/README.md
- 需要翻译的地方添加了特别的标志：`<!-- TODO: translation -->`
- PR #286

后续：完成此合并后，将处理 #217 provide/inject 遗留问题

**Comment by GeekQiaQia** [comment]
同步统一在这个issue下处理吗

**Comment by veaba** [comment]
> 同步统一在这个issue下处理吗

因为这个同步动作的改动比较多，这个 issue 是为了描述本次同步英文仓库（PR #286）内容细节，这是为了方便讨论 PR #286 可能出现的问题而独开的 issue，其他翻译程序按照以前进行。

**Comment by veaba** [comment]
@GeekQiaQia 欢迎大家帮助我们更新到最新版，但这种情况下，可能会有颗粒度比较细的 commit，比如 #278，为了确保不会遗留英文版任何一个commit，我们同时会定期的大面积同步。

这次 PR#285 是定期的同步英文仓库的工作。
