### ISSUE TITLE
[同步]class-and-style.md

### ISSUE THREAD

**Issue by GeekQiaQia** [vuejs/docs-next-zh-cn#288]
同步英文文档：[class-and-style.md](https://github.com/vuejs/docs-next-zh-cn/projects/3#card-44141782)

**Comment by veaba** [comment]
@GeekQiaQia 感谢能够补充遗留的部分，内容较简单的 PR，可以不用开 issue 的。

这其实是属于查漏补缺的部分，正常发起 PR 即可。

**Comment by GeekQiaQia** [comment]
> @GeekQiaQia 感谢能够补充遗留的部分，内容较简单的 PR，可以不用开 issue 的。
> 
> 这其实是属于查漏补缺的部分，正常发起 PR 即可。

好的，明白了
