### ISSUE TITLE
[译法讨论] 自定义指令 - 函数简写 小节的译法讨论

### ISSUE THREAD

**Issue by ShroXd** [vuejs/docs-next-zh-cn#328]
一、原文
1. 中文原文
在很多时候，你可能想在 mounted 和 updated 时触发相同行为，而不关心其它的钩子。比如这样写：
2. 英文原文
In previous example, you may want the same behavior on mounted and updated, but don't care about the other hooks. You can do it by passing the callback to directive:

二、译法问题
1. 关于标题的译法的问题
在英文文档中，标题为 `Function Shorthand`，中文文档翻译为了`函数简写`。我认为这种翻译是有歧义的，应当翻译成`简写函数`。
因为这部分内容不是对函数的简写，而是使用函数简化的原本 Object 式的写法。
文档中提到的写法是将原本 Object 形式的钩子函数配置写成了一个单一的函数，Vue 内部会将这个函数同时应用到 `mounted` 与 `updated` 钩子上。对应源码如下：
```typescript
//  packages/runtime-core/src/directives.ts/withDirectives

if (isFunction(dir)) {
  dir = {
    mounted: dir,
    updated: dir
  } as ObjectDirective
}
```
而`函数简写`的译法则会有歧义，读者可能会以为这个写法是对一个复杂函数的简写。

2. “比如这样写：” 一句的译法有问题
原文是：You can do it by passing the callback to directive
所以中文翻译应当是：你可以通过将这个回调函数传递给指令来实现

三、改进后的翻译

简写函数
在前面的例子中，你可能想在 mounted 和 updated 阶段触发相同的行为，而不关心其他的钩子函数。那么你可以通过将这个回调函数传递给指令来实现：

**Comment by Jinjiang** [comment]
认同，目前的译法确实是有歧义的

**Comment by Jinjiang** [comment]
补充一下，段落描述我做了更改，至于标题是函数简写还是简写函数，坦白说我觉得两者的区别并不大，很难说这个改变会有效减少歧义，所以做了保留。希望我们可以更多的通过段落描述来消除误解吧。🙏
