### ISSUE TITLE
在使用@vue/cl构建ts-vue3项目的时候 shims-vue.d.ts 声明 @vue/runtime-core 导致组件找不到 vue 导出

### ISSUE THREAD

**Issue by Autumn-one** [vuejs/docs-next-zh-cn#334]
构建环境为最新的@vue/cli脚手架，typescript，vue3.0 我需要在所有组件中注入api 于是采用了如下写法  
```javascript
import api from "@/api"
app.config.globalProperties.api = api; // 向所有组件注入 api 对象
```
但是由于我是用了 ts 所以需要声明相应的模块类型，于是我在 shims-vue.d.ts 中追加如下代码
```javascript
declare module '@vue/runtime-core' {
  import { ApiConfig } from '@/api'

  interface ComponentCustomProperties {
    api: ApiConfig;
  }
}
```
添加上述声明之后会造成一个非常糟糕的问题，所有使用到 `import { defineComponent } from 'vue'` 的地方都将报错，报错内容为：
TS2305: Module '"../../node_modules/vue/dist/vue"' has no exported member 'defineComponent'.
但是如果删除上述声明文件中追加的内容就没有问题了。
请问这样的问题怎么解决？

**Comment by veaba** [comment]
hello，这里只负责 Vue 3 文档的翻译问题。

关于 Vue 3 的语法建议你到官方论坛去讨论。

现将 close 该 issue。’
