### ISSUE TITLE
[示例代码]基础-组件基础-监听子组件事件

### ISSUE THREAD

**Issue by aquichita** [vuejs/docs-next-zh-cn#336]
**结合上下文语义此处子组件属性获取描述错误，请确认是否应该为以下所述：**
错误代码块：
```html
<div id="blog-posts-events-demo">
  <div v-bind:style="{ fontSize: postFontSize + 'em' }">
    <blog-post v-for="post in posts" :key="post.id" :title="title"></blog-post>
  </div>
</div>
```
待确认正确代码块：
```html
<div id="blog-posts-events-demo">
    <div v-bind:style="{ fontSize: postFontSize + 'em' }">
        <blog-post v-for="post in posts" :key="post.id" :title="post.title"></blog-post>
    </div>
</div>
```

**Comment by veaba** [comment]
@aquichita  你好，方便提供相关的文件路径吗?
经对比查证，并非看到此部分文档描述有异常。

---------------------------------
**另外，提醒下**，vuejs 3.0 官方域名 `v3.cn.vuejs.org` ，本仓库文档只维护此域名。

我猜你可能找错仓库了。

**Comment by aquichita** [comment]
> @aquichita 你好，方便提供相关的文件路径吗？
> 经对比查证，而不看到此部分文档描述有异常。
> 
> **另外，提醒下**，vuejs 3.0官方域名`v3.cn.vuejs.org`，本仓库文档只维护此域名。
> 
> 我猜你可能找错仓库了。

不好意思，找错仓库了，谢谢提醒
