### ISSUE TITLE
教程中v-if与v-for优先级解释有误

### ISSUE THREAD

**Issue by yunlongduan** [vuejs/docs-next-zh-cn#337]
[https://v3.cn.vuejs.org/guide/list.html#%E5%9C%A8-v-for-%E9%87%8C%E4%BD%BF%E7%94%A8%E5%80%BC%E7%9A%84%E8%8C%83%E5%9B%B4](url)

教程中关于v-if与v-for优先级解释有误，望修正。

**Comment by veaba** [comment]
@yunlongduan 你好，如果可以的话，麻烦贴下截图，或者描述详细的信息吗？

这会方便我们定位问题或者表示不恰当之处。

如果你能够发起 PR 来修复该问题，我们会很高兴看到。

**Comment by yunlongduan** [comment]
![image](https://user-images.githubusercontent.com/33390554/103389674-422fee80-4b4b-11eb-820d-9c2aa72b2413.png)
如上，关于v-for与v-if优先级的解释与风格指南及vue2.x的文档解释存在冲突(有误)。

**Comment by Justineo** [comment]
See https://v3.cn.vuejs.org/guide/migration/v-if-v-for.html.

**Comment by Justineo** [comment]
这是一个 breaking change，文档的描述是没有问题的。

**Comment by Justineo** [comment]
风格指南的描述的确没有更新。

**Comment by yunlongduan** [comment]
好的，这边没太注意到，十分抱歉。感谢您的解答。这个问题我将关闭。
