### ISSUE TITLE
[译法讨论] 处理边界情况 - 低级静态组件与 v-once tip 的译法讨论

### ISSUE THREAD

**Issue by ShroXd** [vuejs/docs-next-zh-cn#347]
一、原文
1. 英文原文
Once again, try not to overuse this pattern. While convenient in those rare cases when you have to render a lot of static content, it's simply not necessary unless you actually notice slow rendering - plus, it could cause a lot of confusion later. For example, imagine another developer who's not familiar with v-once or simply misses it in the template. They might spend hours trying to figure out why the template isn't updating correctly.

2. 中文原文
再次提醒，不要过度使用这种模式。虽然在极少数情况下需要渲染大量静态内容时很方便，但除非你注意到渲染速度——慢，否则就没有必要这样做—另外，这可能会在以后引起很多混乱。例如，假设另一个开发人员不熟悉 v-once 或者只是在模板中遗漏了它。他们可能会花上几个小时来弄清楚为什么模板没有正确更新。

二、译法问题
1. 格式错误
“但除非你注意到渲染速度——慢”，这一句的翻译存在格式问题，导致中文读者很难读懂。

2. 英文中的 it 翻译问题
在英文中，it 可以根据上下文指代一些概念，例如 “it could cause a lot of confusion later”。
但这种便利性翻译至中文后可能会让句子的逻辑显得晦涩难懂，所以我改进了叙述。虽然稍显啰嗦，但却能提高阅读体验。

3. 英文中 EM DASH (—) 的问题
it's simply not necessary unless you actually notice slow rendering - plus, it could cause a lot of confusion later.
在英文中，短破折号有补充说明的意思。在中文中，这个符号需要被替换为逗号、冒号或破折号。基于上下文，这里改成了逗号。
关于这个问题，可以参考 [知乎](https://www.zhihu.com/question/20332423) 上 magasa 的回答。

三、改进后的翻译

再次提醒，不要过度使用这种模式。虽然在需要渲染大量静态内容的极少数情况下使用这种模式会很方便，但除非你注意到先前的渲染速度很慢，否则就没有必要这样做。另外，过度使用这种模式可能会在以后引起很多混乱。例如，假设另一个开发人员不熟悉 `v-once` 或者只是在模板中遗漏了它。他们可能会花上几个小时来弄清楚为什么模板没有正确更新。

**Comment by veaba** [comment]
改进后的阅读会比先前更好了。

**Comment by veaba** [comment]
@ShorXd  非常感谢你的建议，已应用你的 PR。由于被merge pr，现 close 此 issue，如有后续讨论的必要，你可以随时 reopen。

**Comment by veaba** [comment]
@ShroXd Hi，最近 review 有出现 破折号的使用，但现在还不够统一，先到了此前的 #348 中以及此 issue 的提出。

能否请教下，关于破折号的使用。

比如前面提到的：

>“但除非你注意到渲染速度——慢”，这一句的翻译存在格式问题，导致中文读者很难读懂。

在对比下面的：

> 但除非你注意到先前的渲染速度很慢

我个人并不觉得很违和，反而觉得很恰当呢？前面一句能更好的表现语句的重点：“慢”。

（知乎太长太啰嗦了，我就跳过不看了，:joy: ）

**Comment by ShroXd** [comment]
> @ShroXd Hi，最近 review 有出现 破折号的使用，但现在还不够统一，先到了此前的 #348 中以及此 issue 的提出。
> 
> 能否请教下，关于破折号的使用。
> 
> 比如前面提到的：
> 
> > “但除非你注意到渲染速度——慢”，这一句的翻译存在格式问题，导致中文读者很难读懂。
> 
> 在对比下面的：
> 
> > 但除非你注意到先前的渲染速度很慢
> 
> 我个人并不觉得很违和，反而觉得很恰当呢？前面一句能更好的表现语句的重点：“慢”。
> 
> （知乎太长太啰嗦了，我就跳过不看了，😂 ）

Hi~
对于破折号的标准使用，说实话我并没有很系统的研究过，以下皆为一家之言。

“但除非你注意到渲染速度——慢”
在这个句子的修改中，我主要是从阅读体验方面考虑的。尽管这里确实可以认为破折号的作用是解释说明，且突出了“慢”。但这个句子依然很拗口，中文的节奏感被打碎了。
另外的，事实上这部分句子在整体中，是作为“原因”出现的，和后面的“否则就没有必要这样做。”共同叙述了这样一个概念，即：
如果慢，就用这种模式；如果不慢，那就最好别用。

换句话说，如果使用先前的表述，两个子句之间读起来很拗口，读者无法在第一遍阅读时就将这两个子句联系起来考虑。“慢”是很重要，但这句话最主要想告诉读者的是“什么时候使用这个模式”，而不是“慢”。
如果只是想突出“慢”，那更好的办法应该是将其加粗。

以上就是我的理解。
