### ISSUE TITLE
ref && v-for

### ISSUE THREAD

**Issue by JackShell2020** [vuejs/docs-next-zh-cn#357]
#### 官方文档
-  ref 与 v-for 一起使用时，你得到的 ref 将是一个数组，其中包含镜像数据源的子组件。(3.x的文档)
- 当 ref 和 v-for 一起使用的时候，你得到的 ref 将会是一个包含了对应数据源的这些子组件的数组。（2.x的文档）

#### 我的问题
```js
<template>
  <div>
    <p v-for="item of arr" :key="item" :ref="item">{{item}}</p>
  </div>
</template>

<script>
export default {
  data() {
    return {
      arr: [
        'aaaa',
        'bbbb',
      ],
    };
  },
  mounted() {
    console.log(this.$refs.aaaa)
  },
};
</script>
```
- 当 `ref=固定值` 时： `<p v-for="item of arr" :key="item" ref="myP">{{item}}</p>` 
    - 然后 `console.log( this.$refs.myP ) ` 输出的应当是文档中说的数组
- 当 `ref=不是固定值 ` 时： `<p v-for="item of arr" :key="item" :ref="item">{{item}}</p>`
    -  然后 `console.log( this.$refs.aaaa) ` 
    - 在2.x版本中，输出的依然是数组（为什么）
    - 在3.x版本中，输出的确实当前节点（为什么）

**Comment by veaba** [comment]
@JackShell2020  看起来是 Vue 3.x 一个bug，建议你去官方 vue 3仓库中反馈该问题，中文文档仓库无法处理此类问题。

现发现 `v3 英文版` 已移除该段描述，我们将在后续的 `v3 中文版本` 中移除该段描述。

**Comment by veaba** [comment]
相关 PR  #391
