### ISSUE TITLE
v-if的优先级现在比v-for高了，文档中尚未更改

### ISSUE THREAD

**Issue by XingXiaoWu** [vuejs/docs-next-zh-cn#358]
![image](https://user-images.githubusercontent.com/22769131/104678684-ece90500-5726-11eb-8963-70eef346ab12.png)
https://v3.cn.vuejs.org/guide/list.html#%E5%9C%A8-template-%E4%B8%AD%E4%BD%BF%E7%94%A8-v-for
![image](https://user-images.githubusercontent.com/22769131/104678699-f6726d00-5726-11eb-82c1-30532f79eeed.png)
https://v3.cn.vuejs.org/api/directives.html#v-if

**Comment by XingXiaoWu** [comment]
我提交了一个[pr](https://github.com/vuejs/docs-next-zh-cn/pull/359)

**Comment by veaba** [comment]
related #359
