### ISSUE TITLE
认领【已翻译未校对】：src/guide/migration/v-model.md

### ISSUE THREAD

**Issue by zhaozhe0831** [vuejs/docs-next-zh-cn#36]
校对迁移指南中 [`v-model`](https://github.com/vuejs/docs-next-zh-cn/blob/master/src/guide/migration/v-model.md) 部分。

pull request: #39

**Comment by zhaozhe0831** [comment]
![image](https://user-images.githubusercontent.com/12945873/92675563-45ac2980-f352-11ea-9a14-fcd21a34ab60.png)

本地 `npm run serve` 后，打开此[页面](http://localhost:8080/guide/migration/v-model.html#%E6%A6%82%E8%A7%88)有报错情况。

**Comment by zhaozhe0831** [comment]
渲染问题

![image](https://user-images.githubusercontent.com/12945873/92676211-b1db5d00-f353-11ea-90cf-28a38fcc98a0.png)

代码上没有明显区别，渲染出来的页面差别很明显。

**Comment by veaba** [comment]
> ![image](https://user-images.githubusercontent.com/12945873/92675563-45ac2980-f352-11ea-9a14-fcd21a34ab60.png)
> 
> 本地 `npm run serve` 后，打开此[页面](http://localhost:8080/guide/migration/v-model.html#%E6%A6%82%E8%A7%88)有报错情况。

该问题在 #5 中讨论。

**Comment by zhaozhe0831** [comment]
本人译文
![image](https://user-images.githubusercontent.com/12945873/92695609-47d6ae00-f37b-11ea-8009-d48cbeafff9c.png)
他人译文
![image](https://user-images.githubusercontent.com/12945873/92695777-8e2c0d00-f37b-11ea-82af-f3c3194a52b4.png)
官方原文
![image](https://user-images.githubusercontent.com/12945873/92695640-558c3380-f37b-11ea-953b-cd2353283696.png)

我不确定那种翻译更加准确

**Comment by Jinjiang** [comment]
emit (an event) 原则上建议翻译成“触发”，参考 wiki
总体下来我个人感觉“同时支持传入一个 `modelValue` prop 和触发 `update:modelValue` 事件”

**Comment by veaba** [comment]
该 issue 对应 PR #39 ，已 merge 到 master，同步到 project。现在将关闭该 issue
