### ISSUE TITLE
src/guide/data-methods.md

### ISSUE THREAD

**Issue by Amuumuu** [vuejs/docs-next-zh-cn#360]
这些实例 property 仅在实例首次创建时被添加，所以你需要确保它们都在 data 函数返回的对象中。必要时，要对尚未提供所需值的 property 使用 null、undefined 或其他占位的值。

句尾多一个句号。

**Comment by veaba** [comment]
中文一般都在句末补充句号。

**Comment by Amuumuu** [comment]
**该语句末尾有一个多余的句号！**

**Comment by veaba** [comment]
能够提供必要的截图以及链接。

**Comment by Amuumuu** [comment]
[文档地址](https://v3.cn.vuejs.org/guide/data-methods.html)

[源码第28行](https://github.com/vuejs/docs-next-zh-cn/blob/master/src/guide/data-methods.md)

**Comment by veaba** [comment]
@Amuumuu 
非常感谢你的反馈，已修复该问题。
