### ISSUE TITLE
bug: vue3里面ref不能对dom元素设置height这些属性了吗？

### ISSUE THREAD

**Issue by jingleding** [vuejs/docs-next-zh-cn#378]
vue2可以通过this.$refs.xxx.style.height="xxx"这样的方式来设置高度等属性，操作dom，3不支持了吗？用如下方式试了也不行：
<div class="meta" ref="meta">
.................
const meta = ref(null);
meta.style.height = '100%';

**Comment by Justineo** [comment]
本项目只负责处理英文文档的翻译，不负责回答问题，请见谅。
