### ISSUE TITLE
[翻译讨论] 关于文档中指向 mozilla 链接语言统一的问题

### ISSUE THREAD

**Issue by ShroXd** [vuejs/docs-next-zh-cn#389]
## 问题
在文档中，有一些技术术语的链接指向了 mozilla 网站。网站中大多数页面有中文和英文两个版本。`Vue3` 英文文档目前所有链接均指向英文版本的页面。中文文档有些页面指向中文版本，有些却指向了英文版本。需要统一一下。

## 解决方法
初步考虑是在确认链接有效的情况下，将所有链接替换为中文版本的链接。
不过该网站有些页面中文比较晦涩难懂，英文版本质量比较高，所以具体修改成哪一种，有待讨论。

## 补充

目前指向 zh-CN 文档的页面：
- src/api/application-api.md
- src/cookbook/debugging-in-vscode.md
- src/guide/class-and-style.md  246
- src/guide/component-slots.md
- src/guide/routing.md

目前指向 en-US 文档的页面：
- src/guide/application-config.md
- src/guide/basic-reactivity.md
- src/api/directives.md
- src/guide/a11y-basics.md
- src/guide/a11y-semantics.md
- src/guide/change-detection.md
- src/guide/class-and-style.md 15 233
- src/guide/events.md
- src/guide/installation.md
- src/guide/reactivity-fundamentals.md
- src/guide/reactivity.md
- src/guide/keycode-modifiers.md

目前指向 en 文档的页面：
- src/guide/instance.md

**Comment by veaba** [comment]
这里有个场景：MDN 有些汉译页面是积极维护，有些是不积极的，这样就会有落差，存在内容滞后的情况。

根据上面的情况，以及现有的，列出优先级：

- MDN 全部换为英文，由于网站有中文版切换入口，尽管有些页面并没有中文版，总体上问题不是太大。
-  MDN 全部换为中文，但存在问题滞后以及翻译质量不高的情况（但并非影响阅读，大多数情况只是参考描述用法，详细的话可能就是英文版了,有些页面并没有中文版）
  - 基于此项存在 [“有些页面并无中文版”](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles)，可排除此项
- 保持现有（存在链接本地化会被随时替换）
  - 仅当有中文版的情况下使用中文版，否则使用英文版

 为了适当本地化，可以使用中文版，仅当不存在中文版使用英文版，由此可见采纳第 3 条，应该较为恰当。

**Comment by Jinjiang** [comment]
指向中文 MDN 的工作都是我们在翻译的时候顺手改的。考虑到 MDN 的中文文档也不是每篇都有，所以我觉得暂不必做严格的统一

**Comment by ShroXd** [comment]
> 指向中文 MDN 的工作都是我们在翻译的时候顺手改的。考虑到 MDN 的中文文档也不是每篇都有，所以我觉得暂不必做严格的统一

那么是否需要将这部分内容添加至[协作指南](https://github.com/vuejs/docs-next-zh-cn/wiki/%E5%8D%8F%E4%BD%9C%E6%8C%87%E5%8D%97)中？这样后续如果有英文文档的同步工作中涉及到了这个问题，其他人也可以做出正确的更改

**Comment by veaba** [comment]
> > 指向中文 MDN 的工作都是我们在翻译的时候顺手改的。考虑到 MDN 的中文文档也不是每篇都有，所以我觉得暂不必做严格的统一
> 
> 那么是否需要将这部分内容添加至[协作指南](https://github.com/vuejs/docs-next-zh-cn/wiki/%E5%8D%8F%E4%BD%9C%E6%8C%87%E5%8D%97)中？这样后续如果有英文文档的同步工作中涉及到了这个问题，其他人也可以做出正确的更改

关于部分讨论结果，我来同步至 [术语翻译约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A) wiki  CC @Justineo

**Comment by veaba** [comment]
related: https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E5%85%B3%E4%BA%8E-mdn-%E9%93%BE%E6%8E%A5%E7%9A%84%E7%BB%9F%E4%B8%80%E4%BD%BF%E7%94%A8
