### ISSUE TITLE
bug: 移动端这个页面滑动到底部页面一直闪烁

### ISSUE THREAD

**Issue by ibwei** [vuejs/docs-next-zh-cn#407]
- bug 页面：https://v3.cn.vuejs.org/guide/mobile.html#%E4%BB%8B%E7%BB%8D
- bug 说明：这个页面滑动到底部页面一直闪烁，平台：macOS,浏览器：chrome

**Comment by Jinjiang** [comment]
没有重现，有截图或录屏可以提供吗？

**Comment by ibwei** [comment]
https://user-images.githubusercontent.com/25237993/108981390-a7c1d680-76c7-11eb-9a40-958533d7955a.mov

如视频所示，接近网页底部时，在触摸板大幅度往下滑动。

**Comment by ibwei** [comment]
https://user-images.githubusercontent.com/25237993/108981390-a7c1d680-76c7-11eb-9a40-958533d7955a.mov

如视频所示，接近网页底部时，在触摸板大幅度往下滑动。

**Comment by ibwei** [comment]
经检测，英文版同页面没有该 bug。

**Comment by Jinjiang** [comment]
Hi @ibwei 我这边依然没有重现， 我可以贴上我这边看到的截图的情况，并想多确认一些细节：
![image](https://user-images.githubusercontent.com/206848/110196477-c1a9a900-7e7f-11eb-9e9a-6bacd9c379ed.png)
1. 我发现你截图里左侧侧边栏的滚动条离顶栏之间有一定距离，我这边截图里是没有的，想麻烦简单 inspect 一下那边的 DOM 结构是怎样的
2. 从你的录屏来看，页面正文在浏览器中是没有完整显示的，但是也没有看到正文的滚动条。所以想麻烦确认一下页面是不是没有显示完整，正文的部分是否有滚动条存在
谢谢

**Comment by ibwei** [comment]
无法重现了。
