### ISSUE TITLE
翻译讨论：关于 wrapper/wrap 译法

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#413]
Hi：

近期，有团队成员([讨论来源](https://github.com/vuejs/docs-next-zh-cn/pull/401#discussion_r571518282)) 提出，关于 `wrapper/warp` 在文档中的译法存在不一致的问题。

根据搜索，确实存在此情况：

![image](https://user-images.githubusercontent.com/8652596/108630257-d6109d80-749e-11eb-8c40-1b7198636571.png)
![image](https://user-images.githubusercontent.com/8652596/108630266-e1fc5f80-749e-11eb-946e-e89f934168fc.png)

我总结了几个场景下的叫法：

- `包装器` / `包裹器`
- `包装了...` / `包裹了...`
- `包装值` / `包裹值`
- `包装这个对象` / `包裹这个对象`

为了更精确的理解其含义，找了下网络词典，仅供参考：
- [包裹](https://hanyu.baidu.com/s?wd=%E5%8C%85%E8%A3%B9)
- [包装](https://hanyu.baidu.com/s?wd=%E5%8C%85%E8%A3%85)

个人看来，我给 `包装` : `包裹` = `4.5` : `5.5` 这个比例。

CC @Jinjiang @Justineo

**Comment by Jinjiang** [comment]
我倾向于 包裹 和 包裹器

**Comment by Justineo** [comment]
包裹（器）+1

**Comment by veaba** [comment]
总结：

1. 根据讨论结果，现调整 `wrapper/wrap` 的译法，统一为 ：`包裹器/包裹`。

2. 本次结果将同步到[术语翻译约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A)。

3. 后续的将发起新的 PR 来修复该修改。
