### ISSUE TITLE
bug: wiki被保留的英文单复数问题

### ISSUE THREAD

**Issue by ajycc20** [vuejs/docs-next-zh-cn#43]
[被保留的英文单复数问题](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A/c32279a4cf563a576f223c663f0fdb4bab74904f#%E8%A2%AB%E4%BF%9D%E7%95%99%E7%9A%84%E8%8B%B1%E6%96%87%E5%8D%95%E5%A4%8D%E6%95%B0%E9%97%AE%E9%A2%98)

properties -> priperty

**Comment by veaba** [comment]
已修正：properties -> property
