### ISSUE TITLE
在阅读中文文档时发现错误

### ISSUE THREAD

**Issue by Raywh** [vuejs/docs-next-zh-cn#444]
但是，当使用合成 API 显式创建响应式对象时，最佳做法是不要保留对原始对象的引用，而只使用响应式版本
应该是说 组合式 API
还有很多地方 有合成的说法 eg：合成函数等

**Comment by Raywh** [comment]
![image](https://user-images.githubusercontent.com/45505303/113234881-b7d76200-92d4-11eb-881e-e70a1e6a2a8c.png)

**Comment by veaba** [comment]
@Raywh Hi，感谢你的指出，这是我们早期的一个错误的翻译，#446 修复该问题。

如果你后续有发现新的错误，欢迎发起 PR 修复该问题。

（当合并 PR 后，将自动 close 该issue）
