### ISSUE TITLE
阅读文档；文字翻译错误问题

### ISSUE THREAD

**Issue by songxianling** [vuejs/docs-next-zh-cn#445]
https://v3.cn.vuejs.org/api/options-data.html#props 里面的「详细」-第三点「required」中：义该、truthy；第四点「validator」中：falsy 
是否是翻译文字有误呢

**Comment by veaba** [comment]
@songxianling 感谢你的指出。
是的，`义该`，这是一个错别字。刚发起的 #447 将修复该问题。
但后续的，`truthy`、`falsy` 这两个是专业术语，我们保留了原英文。

（#447 被合并后，将自动 close 该 issue。）
