### ISSUE TITLE
[翻译讨论] 关于 `in-DOM` 的翻译

### ISSUE THREAD

**Issue by ShroXd** [vuejs/docs-next-zh-cn#464]
## 问题
对于 `in-DOM` 的翻译存疑。
在 #460 中，@veaba 提到在文档中常用译法为：`in-DOM` -> `内置 DOM`。不过我在文档中依然找到了一些保留了 `in-DOM` 的译法：<br>
```
// src/guide/installation.md    128行
例如，in-DOM 模板或通过内联 JavaScript 字符串的模板

// src/guide/installation.md    140行
即：将字符串传递给 template 选项，或者使用元素的 in-DOM HTML 作为模板挂载到元素
```

## 解决方案
不论 `in-DOM` 还是 `内置 DOM`，都可以忠实的表达原意。
但我认为由于这个词实际上是一个整体，所以为了维持原有的表达力，应当不予翻译。
这样做的好处是，对于类似 `in-DOM HTML` 的词组，读者会很清楚的知道其中的关系。但如果翻译为 `内置 DOM HTML`，读者可能会疑惑，这个 “内置” 到底指的是 DOM，还是 DOM HTML？

**Comment by Justineo** [comment]
“in-DOM”我比较倾向于直接译为“DOM 内”，比如“DOM 内 HTML 模板”。

/cc @Jinjiang @veaba

**Comment by ShroXd** [comment]
补充一下目前两种方案的实际效果：

@Justineo 的方案：
```
// src/guide/installation.md    128行
例如，DOM 内模板或通过内联 JavaScript 字符串的模板

// src/guide/installation.md    140行
即：将字符串传递给 template 选项，或者使用元素的 DOM 内 HTML 作为模板挂载到元素
```

@veaba 的方案：
```
// src/guide/installation.md    128行
例如，in-DOM ( DOM 内)模板或通过内联 JavaScript 字符串的模板

// src/guide/installation.md    140行
即：将字符串传递给 template 选项，或者使用元素的 in-DOM ( DOM 内) HTML 作为模板挂载到元素
```

个人认为第二种方案在翻译第二句这种后边还跟着英文专有名词的句子时，会显得冗长。
第一种方案虽然可能会有搜索效果差的问题，但已经足够表意，不会造成歧义。
所以我比较倾向于 @Justineo  的方案。

**Comment by veaba** [comment]
如无更多的消息补充，本次讨论结果如下：

`in-DOM` ——> `DOM 内`，已同步至：https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A

该 issue 将会在 #460 合并后自动关闭。

**Comment by veaba** [comment]
已全局替换 `in-Dom`，https://github.com/vuejs/docs-next-zh-cn/commit/f95afc33cb2fb221a9c3edd9e2c2b46f8a04dc07
