### ISSUE TITLE
v-if与v-for一起使用的优先级，文档中的说法不一致 

### ISSUE THREAD

**Issue by sebarswee** [vuejs/docs-next-zh-cn#466]
在[教程中](https://v3.cn.vuejs.org/guide/conditional.html#v-if-%E4%B8%8E-v-for-%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8)说的是“当 v-if 与 v-for 一起使用时，v-if 具有比 v-for 更高的优先级。”
而在[风格指南](https://v3.cn.vuejs.org/style-guide/#%E9%81%BF%E5%85%8D-v-if-%E5%92%8C-v-for-%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8%E5%BF%85%E8%A6%81)，详解里面，说的是“当 Vue 处理指令时，v-for 比 v-if 具有更高的优先级”
![image](https://user-images.githubusercontent.com/4177237/114683553-b54c2200-9d42-11eb-8c2d-e7c6dcb40f89.png)
![image](https://user-images.githubusercontent.com/4177237/114683609-c006b700-9d42-11eb-8017-5c76420b1397.png)

**Comment by veaba** [comment]
@sebarswee Hi，感谢指出。这是同步过程中遗漏的内容，现已在 PR #467 中得到更新。

同步完成之后，将会自动关闭此 issue 。
