### ISSUE TITLE
[认领] [已翻译未校对] : src/guide/migration/attribute-coercion.md

### ISSUE THREAD

**Issue by Limiandy** [vuejs/docs-next-zh-cn#474]
已提交了 PR，第一次参与社区贡献，如果参与流程有问题，请指正。

**Comment by veaba** [comment]
已与 #468 申请重复，现 close 该 issue。

可以在 https://github.com/vuejs/docs-next-zh-cn/projects/3 中的  `已翻译待校对` 选择未被标注的，进行申请。

你可以重新打开并修改标题做其他用途。
