### ISSUE TITLE
关于 `Effect Flush Timing` 翻译问题

### ISSUE THREAD

**Issue by ajycc20** [vuejs/docs-next-zh-cn#48]
暂译为 效果冲刷时间 #45 

是否有一个更合理的翻译结果

**Comment by ajycc20** [comment]
对照了composition-api中[watcheffect](https://composition-api.vuejs.org/zh/api.html#watcheffect)和[watch](https://composition-api.vuejs.org/zh/api.html#watch)的英文原文，和v3.vuejs.org是一致的

所以是否这部分的中文翻译可以直接参考composition-api的翻译

**Comment by Justineo** [comment]
就用“副作用刷新时机”吧，composition-api 里的翻译挺好的。

**Comment by ajycc20** [comment]
#50 更新了 `watch` 和 `watchEffect`的翻译

这部分参考了composition-api中 [watcheffect](https://composition-api.vuejs.org/zh/api.html#watcheffect)和[watch](https://composition-api.vuejs.org/zh/api.html#watch)的翻译

**Comment by veaba** [comment]
该讨论已纳入到：[术语翻译约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A)

结论为： `Effect Flush Timing`  翻译为 `副作用刷新时机`。

该 issue 将 close。
