### ISSUE TITLE
翻译不太对：你希望以编程的方式 focus 这个 input 在组件上挂载

### ISSUE THREAD

**Issue by DawnEve** [vuejs/docs-next-zh-cn#480]
https://v3.cn.vuejs.org/guide/component-template-refs.html

原句：
This may be useful when you want to, for example, programmatically focus this input on component mount:

原翻译：
例如，**你希望以编程的方式 focus 这个 input 在组件上挂载**，这可能有用

更好的翻译：
例如，你希望在组件挂载时，以编程的方式 focus 这个 input 上，这可能有用

**Comment by veaba** [comment]
欢迎给我们发起 PR 来修改改问题。

**Comment by DawnEve** [comment]
> 欢迎给我们发起 PR 来修复该问题。

a new Pull request
