### ISSUE TITLE
bug: Broken Links

### ISSUE THREAD

**Issue by skirtles-code** [vuejs/docs-next-zh-cn#483]
你好

Sorry about my use of English.

I ran an internal link checker over the Chinese translation of the Vue 3 documentation. I've listed the broken links below. Hope it helps.

There's one link to a page that doesn't exist:

* Missing page https://v3.cn.vuejs.org/guide/todo:comparison.html
  - Linked from https://v3.cn.vuejs.org/guide/introduction.html

There are several links that use hashes to link to headers that don't exist:

<details>
  <summary>Click for missing hashes</summary>

* Missing hash https://v3.cn.vuejs.org/style-guide/#模板中的组件名大小写-强烈推荐
  - Linked from https://v3.cn.vuejs.org/style-guide/
* Missing hash https://v3.cn.vuejs.org/style-guide/#avoid-v-if-with-v-for-essential
  - Linked from https://v3.cn.vuejs.org/guide/conditional.html
  - Linked from https://v3.cn.vuejs.org/guide/list.html
  - Linked from https://v3.cn.vuejs.org/guide/list
* Missing hash https://v3.cn.vuejs.org/style-guide/#base-component-names-strongly-recommended
  - Linked from https://v3.cn.vuejs.org/guide/component-registration.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/introduction.html#重大改变
  - Linked from https://v3.cn.vuejs.org/guide/migration/introduction.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/introduction.html#支持的库
  - Linked from https://v3.cn.vuejs.org/guide/migration/introduction.html
* Missing hash https://v3.cn.vuejs.org/support-vuejs/#recurring-pledges
  - Linked from all pages in the main navigation
* Missing hash https://v3.cn.vuejs.org/guide/installation.html#explanation-of-different-builds
  - Linked from https://v3.cn.vuejs.org/guide/migration/global-api-treeshaking.html
* Missing hash https://v3.cn.vuejs.org/guide/list.html#displaying-filtered-sorted-results
  - Linked from https://v3.cn.vuejs.org/guide/migration/v-if-v-for.html
* Missing hash https://v3.cn.vuejs.org/guide/component-basics.html#通过-Prop-向子组件传递数据
  - Linked from https://v3.cn.vuejs.org/guide/introduction.html
* Missing hash https://v3.cn.vuejs.org/guide/component-basics.html#dom-template-parsing-caveats
  - Linked from https://v3.cn.vuejs.org/guide/component-basics.html
* Missing hash https://v3.cn.vuejs.org/guide/component-registration.html#local-registration
  - Linked from https://v3.cn.vuejs.org/guide/component-dynamic-async.html
* Missing hash https://v3.cn.vuejs.org/guide/component-props.html#Prop-验证
  - Linked from https://v3.cn.vuejs.org/style-guide/
* Missing hash https://v3.cn.vuejs.org/guide/component-props.html#prop-validation
  - Linked from https://v3.cn.vuejs.org/guide/component-props.html
  - Linked from https://v3.cn.vuejs.org/guide/component-props
* Missing hash https://v3.cn.vuejs.org/guide/component-attrs.html#attribute继承
  - Linked from https://v3.cn.vuejs.org/api/options-data.html
* Missing hash https://v3.cn.vuejs.org/guide/component-custom-events.html#validate-emitted-events
  - Linked from https://v3.cn.vuejs.org/guide/component-basics.html
* Missing hash https://v3.cn.vuejs.org/guide/component-custom-events.html#defining-custom-events
  - Linked from https://v3.cn.vuejs.org/guide/component-attrs.html
* Missing hash https://v3.cn.vuejs.org/guide/component-custom-events.html#handling-v-model-modifiers
  - Linked from https://v3.cn.vuejs.org/guide/migration/v-model.html
* Missing hash https://v3.cn.vuejs.org/guide/transitions-enterleave.html#javascript-hooks
  - Linked from https://v3.cn.vuejs.org/guide/transitions-enterleave.html
  - Linked from https://v3.cn.vuejs.org/guide/transitions-enterleave
* Missing hash https://v3.cn.vuejs.org/guide/transitions-enterleave.html#transitioning-single-elements-components
  - Linked from https://v3.cn.vuejs.org/api/built-in-components.html
* Missing hash https://v3.cn.vuejs.org/guide/composition-api-template-refs.html#template-refs
  - Linked from https://v3.cn.vuejs.org/guide/component-template-refs.html
* Missing hash https://v3.cn.vuejs.org/guide/composition-api-template-refs.html#watching-template-refs
  - Linked from https://v3.cn.vuejs.org/guide/reactivity-computed-watchers.html
* Missing hash https://v3.cn.vuejs.org/guide/render-function.html#Functional-Components
  - Linked from https://v3.cn.vuejs.org/guide/transitions-list.html
* Missing hash https://v3.cn.vuejs.org/guide/reactivity-fundamentals.html#ref-解开
  - Linked from https://v3.cn.vuejs.org/guide/composition-api-setup.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/custom-elements-interop.html#customized-built-in-elements
  - Linked from https://v3.cn.vuejs.org/guide/migration/introduction.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/data-option.html#mixin-merge-behavior-change
  - Linked from https://v3.cn.vuejs.org/guide/migration/introduction.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/fragments.html#overview
  - Linked from https://v3.cn.vuejs.org/guide/migration/custom-directives.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/global-api.html#config-productiontip-removed
  - Linked from https://v3.cn.vuejs.org/guide/migration/global-api.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/global-api.html#config-ignoredelements-is-now-config-iscustomelement
  - Linked from https://v3.cn.vuejs.org/guide/migration/global-api.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/global-api.html#a-note-for-plugin-authors
  - Linked from https://v3.cn.vuejs.org/guide/migration/global-api.html
* Missing hash https://v3.cn.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties
  - Linked from https://v3.cn.vuejs.org/guide/migration/global-api.html
* Missing hash https://v3.cn.vuejs.org/api/application-config.html#globalProperties
  - Linked from https://v3.cn.vuejs.org/api/application-api.html
* Missing hash https://v3.cn.vuejs.org/api/global-api.html#arguments-4
  - Linked from https://v3.cn.vuejs.org/guide/component-dynamic-async.html
* Missing hash https://v3.cn.vuejs.org/api/composition-api.html#lifecycle-hooks
  - Linked from https://v3.cn.vuejs.org/api/composition-api.html
</details>

If you're curious, I wrote the checking tool myself. It's available at https://github.com/skirtles-code/vue-docs-link-checker.

**Comment by veaba** [comment]
@skirtles-code  Wow! Very nice tool !! 

Thank you for checking, we will fix these links later.

👍
