### ISSUE TITLE
bug: watchEffect  监听 ref动态获取元素

### ISSUE THREAD

**Issue by yang867381349** [vuejs/docs-next-zh-cn#485]
我在项目中遇到问题。用watchEffect 来监听 ref动态元素的 scrollLeft 只取值到两次 第三次就不出返回值了？

`

<div class="router-page-box-box" v-for="(item,index) in dataList.router" :key="index">
  <div :ref="item.path === route.path?'activeDiv':''">
    <div class="svg-icon-flex">
      <div @click="routeLinkUrl(item.path)">{{ item.name }}</div>
      <svg class="icon svg-icon" aria-hidden="false" @click="DeleteTag(index)">
        <use :xlink:href="'#iconxwtubiaoku-08'"></use>
      </svg>
    </div>
  </div>
</div>

watchEffect(() => {
      nextTick(() => {
        console.log(activeDiv.value.scrollLeft)
      }
})

`

// watchEffect 默认自己加载一次。
// 我在点击的时候 执行一次
// 两次执行后将会不在执行。

<img width="1134" alt="WechatIMG265" src="https://user-images.githubusercontent.com/20942938/116917831-c1603b00-ac81-11eb-9ae6-b221fa70a2ef.png">

**Comment by veaba** [comment]
Hi, 本仓库不受理关于 vue 的使用问题，如确实是发现 bug，请前往主仓库[发起 issue](https://github.com/vuejs/vue-next/issues/new/choose)。

建议抽离成为小项目到 [codepen.io](https://codepen.io/) 等在线代码平台，以方便复现。
