### ISSUE TITLE
翻译讨论：关于 `unwrap` 的译法

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#487]
来于#436 @Justineo 的提议，现在关于 `unwrap` 有几个候选的译法：

- `解包`
- ~~`解构`~~
- `展开`
- `解开`

原文示例：
- ref will be unwrapped （ref 将会解包/解构/展开/解开）
- if any property uses a `ref` it will be automatically unwrapped when it is accessed via the proxy
- Ref Unwrapping
- `reactive` will unwrap all the deep `ref`, while maintaining the ref reactivity

/cc  @Jinjiang

**Comment by Justineo** [comment]
解构可以直接排除掉，会和 JS 中的 destructrue 概念混淆。

另外 wrap/unwrap 是成对的，如果考虑到对应关系，是不是译为“包裹/解包”更容易对应上？

**Comment by Jinjiang** [comment]
我也觉得“包裹/解包”是 OK 的

**Comment by Jinjiang** [comment]
印象总也有些地方将“unwrap”译为了“展开”，大家觉得哪个更好一些？

**Comment by veaba** [comment]
我在纠结 `展开` <---> `解包` 之间徘徊。

**Comment by veaba** [comment]
`展开` ：更像是一个非人为或者手动之类的描述，带有舒展开来的意思，形象的比喻是 一团纸张，扔在地上，自动舒展看来。

`解包`：带有手动的或工具去操作的那种（CS 中拆炸弹的那种描述？:joy:  ）

**Comment by Jinjiang** [comment]
那就解包吧，刚好今天 VueConf 会上讨论也用的是解包

**Comment by veaba** [comment]
结论：

unwrap 后续将以译为： `解包`。

已同步到 wiki，后续全局修改同步后将 close 该 issue。

**Comment by originalix** [comment]
看文档发现 unwrap 翻译为解构觉得不太妥当，提了个 pr，没想官方已经开了对应 issue

**Comment by originalix** [comment]
> 结论：
> 
> unwrap 后续将以译为： `解包`。
> 
> 已同步到 wiki，后续修改同步全局后将 close 该 issue。

Hi, 看到结论后，全局搜索了一下解构，以及官方文档中使用 `unwrap` 的地方，并进行了替换。 🤝

**Comment by Jinjiang** [comment]
如果已经全局替换过，那我觉得这个 issue 可以做关闭处理了。谢谢大家！
