### ISSUE TITLE
翻译讨论：关于 `CSS Module` 的译法

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#488]
来自 #436 中 @Justineo 的提议：

> CSS Module，实际上是一个特指的技术项目，我建议不翻译。

![image](https://user-images.githubusercontent.com/8652596/117101533-fe731d00-ada8-11eb-88d8-af6f9dbcc2c7.png)

/cc @Jinjiang

**Comment by Jinjiang** [comment]
补充一下我的观点，我发现原文确实有单数且小写的 CSS module，而且不是在讨论 CSS Modules 这个技术，而是单纯在讨论一个 CSS 模块，感觉这里翻译成“CSS 模块”也是可以的。

@Justineo 你怎么看？

**Comment by Justineo** [comment]
这类情况甚至可以有冗余：CSS Modules 模块。当然我觉得 CSS 模块也没到不能接受的程度，毕竟有的时候原文也没有那么严谨。

**Comment by Jinjiang** [comment]
确实原文有些地方也没有特别严谨。那我觉得"The name of the CSS module."这里就翻译为“CSS 模块”好了，别的 case 我们再另外讨论。

**Comment by veaba** [comment]
我了解下来：

仅当说的 CSS Modules 技术的时候，保留原文。

而说的 css 本身的模块，`css module` 还是译为中文。

**Comment by Jinjiang** [comment]
> 而说的 css 本身的模块，css module 还是译为中文。

从有限的例子来看是这样的，如果将来遇到更多例子我们可以再多讨论一下再确定

**Comment by Jinjiang** [comment]
鉴于相关特殊的 case 均已经 review 完毕且长时间没有新的讨论，不介意的话我把这个 issue 关掉了。谢谢
