### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by imtaotao** [vuejs/docs-next-zh-cn#499]
![image](https://user-images.githubusercontent.com/26618593/117973701-483aa500-b35f-11eb-8689-61f8009ad2a1.png)
![image](https://user-images.githubusercontent.com/26618593/117973725-5092e000-b35f-11eb-93c4-d70f9863992d.png)
![image](https://user-images.githubusercontent.com/26618593/117973789-61435600-b35f-11eb-9044-e6a082be327f.png)

加了 base 后，这个打包是不是有点问题，这个是 vuepress 的 bug 还是需要文档自己配的

**Comment by veaba** [comment]
这个自定义的拓展，请参考 vuepress 来自己解决了。
该 issue 超出文档本身的内容， 现在 close 该 issue。
如认为有必要继续沟通，请随时 reopen。
