### ISSUE TITLE
bug：console error report when the scrollBehavior selector is invalid

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#5]
下面有两个bug：

## vue-router 缺陷引发
1. 在生产环境下，直接访问具体的页面，如：/guide/installation.html
再次刷新，控制台报错，进而导致
![image](https://user-images.githubusercontent.com/8652596/91382574-999c1600-e85c-11ea-8c1d-affee4cc7c26.png)
> app.2e9ad43d.js:6 DOMException: Failed to execute 'querySelector' on 'Document': '#%E5%A4%84%E7%90%86%E7%94%A8%E6%88%B7%E8%BE%93%E5%85%A5' is not a valid selector.

相关issue：
- [Scroll behavior: hash that starts with number #2163](https://github.com/vuejs/vue-router/issues/2163) 
- [Header Anchors](https://github.com/vuejs/vuepress/issues/121)
- [vue/rfcs/active-rfcs/0035-router-scroll-position.md](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0035-router-scroll-position.md)
-[Better error message when the scrollBehavior selector is invalid](https://github.com/vuejs/vue-router/issues/3008)

该bug不影响功能，只是无法触发点击h标签，无法滚动

## 进入指南，几个深层的菜单栏无法展开
生产环境下，主页进入起步，两个无法展开迁移侧栏菜单：从Vue 2迁移、贡献文档。（影响使用）
控制台报错。
> app.2e9ad43d.js:6 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

![image](https://user-images.githubusercontent.com/8652596/91382712-eaac0a00-e85c-11ea-93f6-0a74f48b43e3.png)

相关issue：
- [Failed to execute 'appendChild' on 'Node': This node type does not support this method. #1692](https://github.com/vuejs/vuepress/issues/1692)
注：该bug 尚未定位到原因。

**Comment by QC-L** [comment]
问题 1 是因为浏览器访问链接时，转义了中文，在 `querySelector` 时出了问题。
React 和 webpack 目前采用的都是加特殊标识的形式，感觉可以参考。
