### ISSUE TITLE
bug: 关于IE11描述的问题

### ISSUE THREAD

**Issue by pruidong** [vuejs/docs-next-zh-cn#501]
https://v3.cn.vuejs.org/guide/introduction.html#%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%83%E7%B4%A0%E7%9A%84%E5%85%B3%E7%B3%BB

文内提到:

> 并且在所有支持的浏览器 (IE11 及更高版本) 之下表现一致。

但Vue 3.0已明确不支持IE11[(链接)](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0038-vue3-ie11-support.md),建议删除上述描述.

**Comment by veaba** [comment]
我们定期同步英文版内容，建议提 issue 到英文版。
