### ISSUE TITLE
#侦听模板引用中  语句重复了

### ISSUE THREAD

**Issue by myDancer** [vuejs/docs-next-zh-cn#504]
链接： https://v3.cn.vuejs.org/guide/composition-api-template-refs.html#%E4%BE%A6%E5%90%AC%E6%A8%A1%E6%9D%BF%E5%BC%95%E7%94%A8

因此，使用模板引用的侦听器应该用 flush: 'post' 选项来定义，**这将在 DOM 更新后运行副作用，确保模板引用与 DOM 保持同步，并引用正确的元素。这将在 DOM 被更新后运行副作用，并确保模板引用与 DOM 保持同步并引用正确的元素。**

**Comment by renmu123** [comment]
我们正在这个 pr 中讨论一些组合式 API 章节中不太合理的翻译 #492

**Comment by veaba** [comment]
该 issue 已关联 #492，完成后将自动 close
