### ISSUE TITLE
bug: 文档 加入 Vue.js 社区 部分 行为规范链接跳转404

### ISSUE THREAD

**Issue by mistery-li** [vuejs/docs-next-zh-cn#517]

**Comment by veaba** [comment]
麻烦你提供下必要的连接和图片

**Comment by mistery-li** [comment]
> 麻烦你提供下必要的连接和图片

https://vue3js.cn/docs/zh/community/join.html

**Comment by mistery-li** [comment]
![Uploading image.png…]()

**Comment by mistery-li** [comment]
![image](https://user-images.githubusercontent.com/19723639/119071570-a250ff80-ba1c-11eb-9fea-b4af657e3e78.png)
图裂开了，重新上传了一个。不是很了解这种开源bug report 流程，抱歉。周末学习以啊

**Comment by veaba** [comment]
@mistery-li 你好，这个不是我们维护的。

另外，请问一下，我们特地制作了这个 issue 模板难道就没有效果吗？

![image](https://user-images.githubusercontent.com/8652596/119172587-bafefb00-ba98-11eb-93ca-5100e3894f00.png)

**Comment by veaba** [comment]
制作这个 模板的原因，我们是为了防止此种情况，现在看起来，结果似乎不太显著。

**Comment by mistery-li** [comment]
> 制作这个 模板的原因，我们是为了防止此种情况，现在看起来，结果似乎不太显著。

我去了解了解。
