### ISSUE TITLE
关于 “reactive” 和 “reactivity ” 翻译讨论

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#53]
来自 #52 ，@Justineo 的建议：

> reactive 译为“响应式”的话，reactivity 是不是翻译为“响应性”更好？

我摘了英文版实际例子来对比下。

|例子|代入翻译|
|----|----|
|reactive proxy |响应式prop|
|reactive state |响应式状态|
|reactive property|响应式 property||
|reactivity tracking|响应性追踪|
|losing reactivity|丢失响应性|
|reactivity system|响应性系统|

这个术语翻译，据我所知，改动可能比较广泛，现独立 issue ，做为专门的讨论。

@Justineo @Jinjiang

**Comment by Justineo** [comment]
不是要把响应式换成响应性，是形容词用响应式，名词用响应性。

**Comment by veaba** [comment]
> 不是要把响应式换成响应性，是形容词用响应式，名词用响应性。

移除了那段描述。:laugh:

**Comment by Jinjiang** [comment]
> 形容词用响应式，名词用响应性

我比较赞同这个观点，其实用哪种翻译不太会影响到大家理解或产生歧义，更多的是让中文阅读体验更顺畅。所以我觉得即便根据具体翻译做灵活选择也是完全可以接受的。

谢谢

**Comment by veaba** [comment]
@Justineo @Jinjiang ,现在将 close 这个 issue，并同步到 [wiki](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A) ，结论如下：

形容词 `reactive`  译为 `响应式`，名词 `reactivity` 用 `响应性`
