### ISSUE TITLE
翻译讨论：关于 `tree-shaking` 译法问题

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#548]
来自 #535 中，@Justineo 中提到，关于 `tree-shaking`：

> 我理解翻译以后一般不保留时态、复数等变形的，因为汉语里面不会根据这些去理解英文概念的意思。

以及来自 #539：

> tree-shake 是动词，tree-shaken 是完成时，tree-shaking 是进行时当名词用。

个人的回复是：

> 中文里它更像是用以 tree-shaking 形式作为一个通用的叫法，表现的是一种技术术语。

实际上，在 [rollup官网中](https://rollupjs.org/guide/en/)，`tree-shaking` 出现了 21 次。

在国内通常的叫法也是 `tree-shaking`，我们是不是可以认为它更像是一种【技术术语】的名词，而非汉译时候更改时态呢？

召唤 @Jinjiang @Justineo

**Comment by Jinjiang** [comment]
我建议动词时用 tree-shake，名词时用 tree-shaking

**Comment by Jinjiang** [comment]
> 我建议动词时用 tree-shake，名词时用 tree-shaking

鉴于长时间没有更多讨论，我们可以以此达成共识吗？印象中 @Justineo 在之前一些 PR 中也发表过类似的观点。

**Comment by Justineo** [comment]
我理解 tree-shaking 在中文版肯定不合适做为动词用，不过的确作为一个名词/概念来讲，tree-shaking 可能见得多一点。如果能接受两种的话，就都保留吧。如果只保留一个，那我觉得肯定不能是 tree-shaking。

**Comment by Jinjiang** [comment]
OK，那就都保留了
