### ISSUE TITLE
Suggest: Vue3.0 文档  跨域切换 中英文翻译路由指向问题

### ISSUE THREAD

**Issue by NaCoLiu** [vuejs/docs-next-zh-cn#549]
Vue3.0 文档  切换中英文语言时 没有直接路由指向当前看到的页面 而是直接到 中文官网，这个操作很影响用户体验，身边很多都有这个建议，所以提交到这里， 麻烦回复一下 看是否能解决这个问题

**Comment by NaCoLiu** [comment]
建议对文档系统的 翻译项进行修改 获取到当前路由直接指向到中文站的路由

**Comment by Jinjiang** [comment]
认同。但建议把这个意见直接提给英文站，因为其它语言肯定也有同样的问题，这不应该是一个只针对中文版做的改动。希望你可以理解。谢谢

**Comment by NaCoLiu** [comment]
好的 谢谢

**Comment by QC-L** [comment]
@Jinjiang Vite 目前的解决方案是在标题后添加 

`中文标题 {#英文标题对应的锚点}`

然后读取处理锚点时，获取英文标题对应的锚点信息，进行跳转，可以达到与英文一致的情况

**Comment by Jinjiang** [comment]
目前根据我的观察中英文官网都已经支持了这个特性，所以这个 issue 我关掉了。谢谢大家
