### ISSUE TITLE
bug: Vue3.x时，vm.fullName = 'John Doe' ，setter 不会被调用

### ISSUE THREAD

**Issue by linhuakun** [vuejs/docs-next-zh-cn#559]
代码演示
![image](https://user-images.githubusercontent.com/72332066/121358743-6c40d480-c965-11eb-9481-d34ea46f0c22.png)

**Comment by linhuakun** [comment]
![Uploading image.png…]()
3.x文档依旧保证和2.x一样

**Comment by Alanscut** [comment]
Vue 3 中没有将 Vue 实例的data/computed等属性暴露出去，不能按照 Vue 2 的方式操作，此处确实有问题。

**Comment by Jinjiang** [comment]
抱歉这里无法产生足够的讨论，仅做文档翻译用，感谢理解
