### ISSUE TITLE
bug: 使用setup语法糖  => 导致build之后页面空白 无报错信息

### ISSUE THREAD

**Issue by 601157475** [vuejs/docs-next-zh-cn#566]
![image](https://user-images.githubusercontent.com/32232766/122718684-d2035980-d29f-11eb-97d4-55fc29faf589.png)
![image](https://user-images.githubusercontent.com/32232766/122718778-e9424700-d29f-11eb-95ef-5bb86a207465.png)

**Comment by veaba** [comment]
这里仅处理和中文版文档相关的问题，不接受用法问题的咨询，谢谢。
