### ISSUE TITLE
bug: 访问 https://v3.cn.vuejs.org/ 异常

### ISSUE THREAD

**Issue by eyea** [vuejs/docs-next-zh-cn#570]
访问 v3.cn.vuejs.org 发生异常，错误如下：
DNS_PROBE_FINISHED_NXDOMAIN
麻烦修复下，感谢~

**Comment by veaba** [comment]
能否截图下，并描述下操作系统、浏览器、地点的相关信息。

我认为应该与你的网络有关，无关文档网站部署的本身，我们只能记录一下，并找其他用户验证。

**Comment by eyea** [comment]
谢谢 是我的网络设置有问题，已经解决~
再次感谢~
