### ISSUE TITLE
bug: <style vars> has been replaced by a new proposal

### ISSUE THREAD

**Issue by ytx222** [vuejs/docs-next-zh-cn#577]
在迁移到vue3中的新特性中,
https://www.vue3js.cn/docs/zh/guide/migration/introduction.html#%E5%80%BC%E5%BE%97%E6%B3%A8%E6%84%8F%E7%9A%84%E6%96%B0%E7%89%B9%E6%80%A7
新特性第7项(单文件组件状态驱动的 CSS 变量 (<style vars>))
中文版指向的地址 https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-style-variables.md
英文版指向的地址 https://github.com/vuejs/rfcs/blob/style-vars-2/active-rfcs/0000-sfc-style-variables.md

我按照中文版地址所说的新特性进行了学习并写在我的demo中,然后编译提示
```
Module Error (from ./node_modules/vue-loader/dist/index.js):
<style vars> has been replaced by a new proposal: https://github.com/vuejs/rfcs/pull/231
```

所以中文版的地址需要更新,与英文版的一致

**Comment by veaba** [comment]
@ytx222 

你好，这个站点不是我们维护的。

另外，请问一下，我们提供了这个 issue 模板并做了特别说明。想确认一下您在创建 issue 的时候是否是经过这里创建的并留意到了这段描述？

![](https://user-images.githubusercontent.com/8652596/119172587-bafefb00-ba98-11eb-93ca-5100e3894f00.png)

**Comment by ytx222** [comment]
抱歉,我没有详细的检查域名是否一致,只是凭感觉觉得vue3js.cn是官方域名...
不好意思,是我的问题
