### ISSUE TITLE
bug: 站点证书到期了

### ISSUE THREAD

**Issue by weiquanju** [vuejs/docs-next-zh-cn#580]
![image](https://user-images.githubusercontent.com/13448091/124887409-bc17c780-e007-11eb-9037-dcf603b39e60.png)

**Comment by veaba** [comment]
vue3js.cn 这不是官方域名，我们无法也无意处理这个问题。谢谢

另外，请问一下，我们提供了这个 issue 模板并做了特别说明。想确认一下您在创建 issue 的时候是否是经过这里创建的并留意到了这段描述？

![](https://user-images.githubusercontent.com/8652596/119172587-bafefb00-ba98-11eb-93ca-5100e3894f00.png)
