### ISSUE TITLE
感觉这个翻译不通顺：`$data` 周围的响应式代理将追踪 property `val1` 和 `val2` 在该副作用运行时的读取。

### ISSUE THREAD

**Issue by xuzuodong** [vuejs/docs-next-zh-cn#604]
针对原文[这一部分](https://v3.vuejs.org/guide/reactivity.html#how-vue-tracks-these-changes)中的这句话：
> ... The reactive proxy around `$data` will track that the properties `val1` and `val2` were read while that effect is running.

目前的翻译是：
> ... `$data` 周围的响应式代理将追踪 property `val1` 和 `val2` 在该副作用运行时的读取。

问题：
1. 其中 “The reactive proxy around `$data`” 被直译成了 “`$data` 周围的响应式代理”。个人认为翻译成“包裹 `$data` 的响应式代理”更加容易理解，因为中文语境中没有对应的说法。
2. "that" 后面的部分翻译得不知所云：“在该副作用运行时的读取？”不知道是啥意思。

个人认为整句话可以改成：

> 包裹 `$data` 的响应式代理将会追踪到，当副作用运行时，property `val1` 和 `val2` 被读取了。

如果有更容易理解或更准确的译法，欢迎讨论。

**Comment by watonyweng** [comment]
@xuzuodong 欢迎贡献
