### ISSUE TITLE
defineasynccomponent  传入对象 案例代码中 loader 一行 少`,`

### ISSUE THREAD

**Issue by Lzy49** [vuejs/docs-next-zh-cn#608]
[vue 文档](https://v3.cn.vuejs.org/api/global-api.html#defineasynccomponent ) 中 传入 object js 案例中少了一个`,`（英文版有同样bug)
![image](https://user-images.githubusercontent.com/26904555/127498853-808b6b6e-af76-4eff-9965-25c1e02721fe.png)

**Comment by veaba** [comment]
Hi，可以访问这个错误发起 PR 来修复吗？顺便也往英文版的仓库也丢个 PR。

**Comment by Jinjiang** [comment]
这个改动应该没什么悬念，中文版的我直接改掉好了。谢谢

**Comment by Jinjiang** [comment]
英文版：https://github.com/vuejs/docs/pull/1155
