### ISSUE TITLE
关于 prop drilling 如何翻译的问题

### ISSUE THREAD

**Issue by wxsms** [vuejs/docs-next-zh-cn#613]
见：#602 

个人意见应该翻译为“参数透传”，如果尊重 prop 不翻译原则，则为“prop 透传”

**Comment by veaba** [comment]
可以翻译为 “prop 透传”

**Comment by Jinjiang** [comment]
跟周围几个朋友小范围讨论过一次，可能最终觉得“prop 逐级透传”比较精准一些。

**Comment by wxsms** [comment]
> 跟周围几个朋友小范围讨论过一次，可能最终觉得“prop 逐级透传”比较精准一些。

赞同，如无异议的话我可以发起 PR
