### ISSUE TITLE
某些篇章的翻译读起来很像机翻，或者像是太过拘泥于原文，不通顺。

### ISSUE THREAD

**Issue by wxsms** [vuejs/docs-next-zh-cn#618]
举例：

> 这些规则会帮你规避错误，所以学习并接受它们带来的全部代价吧。

这句话得读好多次才能勉强看懂。

> 但如果你想看看模板的功能具体是怎样被编译的，可能会发现会非常有意思。

就很像机翻。

> 在数据的 property 发生冲突时，会以组件自身的数据为优先。

按照中文习惯，应该翻译为“优先使用组件自身的数据”。

> 它不应该被用在生产环境。

按照中文习惯，应该翻译为“生产环境请勿使用”。

> 反例、好例子

第一，应该翻译为“好的例子”，或者“正面例子”。第二，原文是 Good / Bad，没有带 example，如果尊重原文，应该翻译为优 / 劣。

------

总之，这类翻译读起来挺累人的，有时候感觉还不如读英文。相比较来说 React 的中文文档 [https://zh-hans.reactjs.org/](https://zh-hans.reactjs.org/) 就好读很多。

不知道项目组是否欢迎针对此类翻译的“精修”？如果可以的话，我接下来可以花一点时间来做这事。

**Comment by veaba** [comment]
欢迎继续完善翻译内容。

**Comment by Jinjiang** [comment]
@wxsms 首先要感谢你的参与。其次，翻译不是一次性的工作，它可以是一个持续讨论和改进的过程，我相信你会认同。第三，评价别人的翻译质量本身不会对这个项目或社区有实质性的正向帮助。我个人也不鼓励在这个方向上继续讨论。
与其讨论这些事情，我们不妨就事论事，把讨论的重点放在更好的译法是什么上，并鼓励以 issue 或 PR 的形式就事论事地直接提出你的改进建议。
另外我已经看到了你的 PR，其中主观评价翻译质量的文字内容我会删掉或调整——我希望这是我们讨论问题的基础，希望你不要介意。🙏

**Comment by wxsms** [comment]
@Jinjiang 理解，我也发现太多的评价可能影响不好，因此关闭了issue．如果有做得不好的地方，请继续指正！
