### ISSUE TITLE
关于“breaking” 翻译问题 

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#62]
目前关于 “breaking” 的翻译似乎不是很友好，是否保持原版?

@Jinjiang @Justineo

**Comment by zhaozhe0831** [comment]
我觉得可以不翻译，用breaking。

**Comment by veaba** [comment]
> 移除

新闻当中也提及，比如：breaking news，突发新闻的意思。

程序中，大意是：某个功能或者特性，有很大的变化，现在文中，我使用了：“重大变化” 一词。

后面的翻译，我又尝试使用了“突破性” 一词。

**Comment by Justineo** [comment]
我在别的项目的changelog里面一般写：非兼容性变更。

**Comment by zhaozhe0831** [comment]
非兼容，我觉得可以，用来当tag



---原始邮件---
发件人: "GU Yiling"<notifications@github.com&gt;
发送时间: 2020年9月19日(周六) 上午8:23
收件人: "vuejs/docs-next-zh-cn"<docs-next-zh-cn@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Isaac"<zhaozhe0831@vip.qq.com&gt;;
主题: Re: [vuejs/docs-next-zh-cn] 关于“breaking” 翻译问题  (#62)




 
我在别的项目的changelog里面一般写：非兼容性变更。

**Comment by Jinjiang** [comment]
同意用“非兼容”或“不兼容”

**Comment by veaba** [comment]
以上总结：tag 处，使用：“非兼容”，语境下看情况使用 “不兼容”、“非兼容”，该讨论已经同步 [术语翻译约定 wiki](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A)  ， issue 关闭。

**Comment by yangmingshan** [comment]
我一般把"breaking changes"翻译为"破坏性变更"。
