### ISSUE TITLE
v-if和v-for谁的优先级更高？

### ISSUE THREAD

**Issue by wo-yun** [vuejs/docs-next-zh-cn#620]
在vue2.x文档中写的是：v-for 的优先级比 v-if 更高
![image](https://user-images.githubusercontent.com/26746591/128281704-7ceccc04-1527-436a-afb5-079611de9ed3.png)
在vue3文档中写的是：v-if 的优先级比 v-for 更高
![image](https://user-images.githubusercontent.com/26746591/128281843-514593d2-b549-4a20-991d-c8acf80abd58.png)
疑问：是文档写错了？还是因为版本升级，vue3中v-if的优先级比v-for高了

**Comment by Justineo** [comment]
https://v3.cn.vuejs.org/guide/migration/v-if-v-for.html
