### ISSUE TITLE
关于译法优化的建议

### ISSUE THREAD

**Issue by konpeki622** [vuejs/docs-next-zh-cn#626]
基于[#618 ](https://github.com/vuejs/docs-next-zh-cn/issues/618)，结合自己过去在一些翻译工作中的体会，我的想法如下：

1. 外文和中文的语序不同，在翻译时需要调整主谓宾的语序。如果仅是把词语翻译过来，读者在阅读时还是需要自行转义。
2. 外文中代词较少，每句话会使用很多名词来完成语义，而中文不同，在相邻的几句话中重复出现的名词可以省略，使语句不再繁琐，更有利于理解。
3. 为了使语句通顺，可以补充一些过渡关联词。

这些建议基于同一个出发点：使读者理解起来更加容易。不过这会是一个比较大的工作量，成为一个长期的工作，就像是代码重构。

**Comment by Jinjiang** [comment]
很好的建议👍我建议这部分工作可以作为一项长期的工作，鼓励大家在查阅文档的时候如果发现更好的译法可以随时创建 PR。

不介意的话是否可以根据您的经验提供一些直观的例子？这样可以帮助大家更好的实践。同时我可以把这些建议整理到翻译须知里。

谢谢

**Comment by Justineo** [comment]
我觉得有一些大家的共识可以落到 wiki 里面，成为一个更加通用的 guideline。@konpeki622 提的几点简单来说就是：

1. 将没有必要的被动语态改为主动语态，按中文习惯调整语序
2. 移除没有必要的“你的”、“我的”
3. 补充一些：“了”、“的” 之类的辅助表达

1 再补充一些，比如有些词在英文中名词可以当动词用，但是不符合中文的习惯，比如 https://github.com/vuejs/docs-next-zh-cn/pull/624 里有一段“alias `vue` to `@vue/compat`”，不太适合译为“将 `vue` 别名为 `@vue/compat`”，而是“将 `@vue/compat` 设置为 `vue` 的别名”。

**Comment by konpeki622** [comment]
感谢@Jinjiang ，我找了一些简单的例子来说明。

1. 调整语序为中文习惯，例如：

> So far we've only been binding to simple property keys in our templates. But Vue.js actually supports the full power of JavaScript expressions inside all data bindings.

可以译为“目前我们都是只通过模板语法绑定简单的 property 键值，但实际上，Vue.js 完全支持在所有的数据绑定中使用 JavaScript 表达式。”

2. 省略部分在外语中仅用于完成句式的词语，例如：

> When Vue is updating a list of elements rendered with v-for, by default it uses an "in-place patch" strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index.

像`to match the order of the items`这样的短语可以在保证语义不变的条件下简化，译为“Vue 默认按照“就地更新”的策略来更新通过 `v-for` 渲染的元素列表。当数据项的顺序改变时，Vue 不会移动 DOM 元素的顺序，而是就地更新每个元素，确保它们在指定的索引位置上渲染。”

3. 在句子之间补充类似“然而”、“并且”、“即使…也…”这样的关联词，使句子更加连贯，例如：

> The mustache tag will be replaced with the value of the msg property from the corresponding component instance. It will also be updated whenever the msg property changes. 

后半句可以译为“**只要**绑定的组件实例上 `msg` property 发生改变，插值处的内容**就**会随之更新”。

不过我看得没有很细致，可以找出更加简洁的句例，作为典型放入翻译须知。 @Justineo 概括的没有问题，但是希望须知中能结合总结性语言和示例来说明，因为语言很灵活，像这样具体地列出来，想要概括全面是很难的。

**Comment by Justineo** [comment]
可以把看到有问题的地方做即时的修改，我之前针对 Vue 2 的文档做了一些[类似的修缮](https://github.com/vuejs/cn.vuejs.org/pulls?q=is%3Apr+author%3AJustineo++refine)，Vue 3 的文档我们也可以这样一篇一篇来改善。

**Comment by KimYangOfCat** [comment]
> 我觉得有一些大家的共识可以落到 wiki 里面，成为一个更加通用的 guideline。@konpeki622 提的几点简单来说就是：
> 
> 1. 将没有必要的被动语态改为主动语态，按中文习惯调整语序
> 2. 移除没有必要的“你的”、“我的”
> 3. 补充一些：“了”、“的” 之类的辅助表达
> 
> 1 再补充一些，比如有些词在英文中名词可以当动词用，但是不符合中文的习惯，比如 #624 里有一段“alias `vue` to `@vue/compat`”，不太适合译为“将 `vue` 别名为 `@vue/compat`”，而是“将 `@vue/compat` 设置为 `vue` 的别名”。

同意，补充形成 guideline ，以后就能减少翻译优化的工作量。

**Comment by wxsms** [comment]
> 这些建议基于同一个出发点：使读者理解起来更加容易。

个人觉得可以稍微补充一下：在尽可能地尊重原版内容的前提下，使读者理解起来更加容易。即，在修缮的同时，要保证译文所传达的内容（而非句式、语法等）是可信赖的。

虽然将会是很大的工作量，也会是一个长期的工作，不过我愿意加入并做出一些微小的贡献。

**Comment by konpeki622** [comment]
good，我认为还有很多难意识到的点，需要在实践中总结，欢迎积极提出。

**Comment by Jinjiang** [comment]
我把这里列出来的建议整理到了 wiki 里：
https://github.com/vuejs/docs-next-zh-cn/wiki/%E5%8D%8F%E4%BD%9C%E6%8C%87%E5%8D%97

如果需要更多后续讨论的话可以再单开 issue
谢谢
