### ISSUE TITLE
关于 build 一词作名词时的译法讨论

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/docs-next-zh-cn#628]
如题，之前 build 不论用做动词还是名词的时候都被译为了“构建”。如 https://github.com/vuejs/docs-next-zh-cn/pull/624/#discussion_r684877250 中提到的，希望可以进一步讨论一下作名词的时候的译法。

谢谢

**Comment by wxsms** [comment]
**关于 build 一词：**

可以参考[v2文档](https://cn.vuejs.org/v2/guide/installation.html#%E5%AF%B9%E4%B8%8D%E5%90%8C%E6%9E%84%E5%BB%BA%E7%89%88%E6%9C%AC%E7%9A%84%E8%A7%A3%E9%87%8A)：

此处，builds 被翻译为了“构建版本”。我认为可以沿用。

------

**关于 #624 的 “migration build”：**

如果按照以上规则来说，这里应该叫“迁移构建版本”。
不过我个人认为依然是有些难以理解。“用于迁移的构建版本”是否更好呢？

**Comment by Justineo** [comment]
> 用于迁移的构建版本

我觉得可以

**Comment by Jinjiang** [comment]
那就定为“构建版本”了。wiki 已更新。做完全文替换之后该 issue 可关闭。
谢谢。
