### ISSUE TITLE
关于某些英文语境下的“梗”的译法问题

### ISSUE THREAD

**Issue by wxsms** [vuejs/docs-next-zh-cn#632]
举例：

> This is the official style guide for Vue-specific code. If you use Vue in a project, it's a great reference to avoid errors, _**bikeshedding**_, and anti-patterns.

其中这个 bikeshedding 目前的译法是“小纠结”，然而就我的个人感受而言，这个译法应该还有优化空间。

这里涉及到一个“梗”应该如何翻译的问题，可能的做法有：

1. 尝试去以简短的词汇来解释这个“梗”，比如“小纠结”
2. 尝试找到中文语境中类似的“梗”
3. 直接按字面翻译，或者直接不翻译，并添加标记注释，详细地解释这个梗
4. （也许还有其它的方法？）

我个人觉得，也许 2 跟 3 的做法会让读者阅读起来更为轻松。（也许这个问题确定最终方案后也可以加入到 guideline 中？）

**Comment by Justineo** [comment]
这种其实属于英文中有一个特定单词描述，而中文中没有直接对应的词，需要解释清楚需要更多空间的情况。
我更倾向于用中文把意思表达出来，稍微改写一下顺序或者表达方式我都能接受。比如：

> 避免错误和反模式，减少对细枝末节的过度纠结。

**Comment by wxsms** [comment]
> 避免错误和反模式，减少对细枝末节的过度纠结。

这个描述确实好了很多 👍

**Comment by Justineo** [comment]
我建议这种还是 case by case 来处理，应该也不是太多。

**Comment by wxsms** [comment]
@Justineo 理解，根据你的建议更新了我的 PR，读起来顺畅了很多，赞。后续 PR 合并后将会自动关闭掉这个 issue。

**Comment by Jinjiang** [comment]
我也认同 case by case 讨论，而且 bikeshedding 这个词在 Vue 2 的文档里就讨论过了，对此我也没有什么异议。

**Comment by Jinjiang** [comment]
这个 issue 看上去没有更多讨论了，不介意的话我关掉了，谢谢支持
