### ISSUE TITLE
认领已翻译未校对：【校对】：src/guide/typescript-support.md

### ISSUE THREAD

**Issue by QC-L** [vuejs/docs-next-zh-cn#64]

**Comment by xutaogit** [comment]
校对 typescript-support @veaba @QC-L 。

ps：不好意思刚才误操作建了一个空 issue，麻烦关一下。感谢

**Comment by xutaogit** [comment]
@QC-L 不好意思，想问下校验完成后如何提交。我注意到 PR 目前是没有开放的，还是说要成为 contributor 才能参与吗

**Comment by QC-L** [comment]
- -这个是我认领的，你要自己去创建 issues
