### ISSUE TITLE
翻译讨论：关于 `Effect Scope` 译法

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#657]
目前关于 `effect-scope.md` 翻译有重复 PR:

- #655，译为：`副作用范围`
- #648，译为：`域内作用`

**Comment by veaba** [comment]
个人提一个：`副作用域`

**Comment by Yukon123** [comment]
个人感觉 `副作用范围` 可能会更好些,我们可以一眼看出 `副作用` 和 `范围` 两个关键词,`副作用域`很简洁也很妙,但是可能会有些断句误解,    eg: `副`  `作用域` .

**Comment by wxsms** [comment]
> `副作用域`很简洁也很妙,但是可能会有些断句误解, eg: `副` `作用域` .

如果上下文中 `副作用` 这个词频繁出现的话，那么大概不会产生断句的误解？不过这个可能确实是一个迷惑点。

------

我的想法是，不翻译 effect scope 这个词可能更好。因为它是特指 `const scope = effectScope()` 这个 API，翻译了反而可能会让人觉得更迷惑（因为跟 API 就不能一下子对应上了，可能要查一下原文才知道，哦原来这个 `副作用域` 说的是 `effect scope`）。

这种情况还挺常见的，以我读各种技术的中文文档的经验来说。

**Comment by Justineo** [comment]
之前和 @yyx990803 讨论他的意见：

标题里不翻译，正文里直接翻译为“作用域”。另外 effect 翻译成“作用”，不需要“副”。

**Comment by wxsms** [comment]
@Justineo 标题不翻译是非常赞同的。但是“作用域”的话，实际上是把 `effect` 忽略掉了吧，只剩下了 `scope`。

**Comment by Justineo** [comment]
> 但是“作用域”的话，实际上是把 `effect` 忽略掉了吧，只剩下了 `scope`。

不是的，这个逻辑里面其实是 effect = 作用，scope = 域。

**Comment by veaba** [comment]
@Justineo 关于正文的问题，【​effect 翻译成“作用”，不需要“副”。】，是不是有针对性的呢，比如这里说的就是 `effect-scope.md`。

过往，我们有大量的 `Effect` 被译为 `副作用`，这会出现好几个场景的叫法：

- 作用域
- 清除副作用
- 副作用刷新时机
- 执行副作用
- `Effect  Scope` 

尝试一下：

-  `Effect` 保留原文，比如 `Effect scope` 译为 `Effect 作用域`

参考一下：

- 作用域链（Scope Chain）

**Comment by wxsms** [comment]
> 这个逻辑里面其实是 effect = 作用，scope = 域。

这个，个人觉得有点隐晦了。因为“作用域”是一个常用词，通常来说就是代表 `scope` （Google 翻译也是将作用域翻译为了 scope）。要理解到里面还有一层 `effect` 的意思，可能比较难。

> Effect 保留原文，比如 Effect scope 译为 Effect 作用域

赞同这个方案。参考 React [Effect hooks](https://zh-hans.reactjs.org/docs/hooks-effect.html) 章节，里面有大量 effect 没有被翻译。只有少量在合适的上下文种被翻译为了“副作用”。

**Comment by Justineo** [comment]
> * `Effect` 保留原文，比如 `Effect scope` 译为 `Effect 作用域`

我觉得这个可以，统一不翻译 effect 了，可能可以在首次出现的时候解释一下。

**Comment by Jinjiang** [comment]
我这边没有问题，可以这样实践一下看看读者的反馈
btw 我理解 side effect 才是“副作用”，effect 本身就是作用或效果的意思

**Comment by Yukon123** [comment]
> 我这边没有问题，可以这样实践一下看看读者的反馈
> btw 我理解 side effect 才是“副作用”，effect 本身就是作用或效果的意思

完全同意  effect 是效果也是一个函数  最好保留effect本身   effect 在响应式原理里面说过是一个函数的包裹器

**Comment by Yukon123** [comment]
之前首次看文档的时候,对副作用这个也是很怪,自己查了wiki,看了源码也觉得这样翻译不是很妥当.如果保留英文是最好的.

**Comment by Jinjiang** [comment]
那就这么定了，我更新到 wiki
