### ISSUE TITLE
在script setup语法中如何实现{...toRef(state)}的写法呢

### ISSUE THREAD

**Issue by jzfai** [vuejs/docs-next-zh-cn#664]
<template>
  <div id="DemoTest">
    <div>{{stateDemo}}</div>
  </div>
</template>

<script>
import { defineComponent,reactive,toRefs} from 'vue'
// import validMixins from '@/mixins/validMixins.js'
export default defineComponent({
  setup(){
    let state = reactive({stateDemo:1})
    
    return{
      ...toRefs(state)
    }
  }
})
</script>

//script setup写法

<template>
  <div id="DemoTest">
    <div>{{stateDemo}}</div>
  </div>
</template>

<script setup>
import { defineComponent,reactive,toRefs} from 'vue'
// import validMixins from '@/mixins/validMixins.js'
let state = reactive({stateDemo:1})

//无效
...toRefs(state)
  
//有效
let {stateDemo}  = toRefs(state)
</script>

**Comment by veaba** [comment]
抱歉，这里无法产生足够的讨论，本仓库 issue 仅做文档翻译用，感谢理解。
