### ISSUE TITLE
bug: 需要h函数使用的详细参数结构

### ISSUE THREAD

**Issue by linjiahao962889027** [vuejs/docs-next-zh-cn#668]
在我使用vue 3.2.4的时候，配合element-plus的msgbox组件构建自定义的输入的时候，事件无法绑定。
我的问题及代码如图所示：
![屏幕截图 2021-08-20 171352](https://user-images.githubusercontent.com/46292984/130210787-56624d2d-f00a-4c4e-a01a-5934e8de6ea8.png)
![屏幕截图 2021-08-20 171421](https://user-images.githubusercontent.com/46292984/130210805-18a16076-babe-44ff-bc87-dfe8299035d6.png)

**Comment by arronKler** [comment]
vue3 中的直接写 onClick，不需要像 vue2中一样在 on 对象下再写 click。
[https://v3.cn.vuejs.org/guide/render-function.html#v-on](https://v3.cn.vuejs.org/guide/render-function.html#v-on)

**Comment by Justineo** [comment]
文档里有描述了。不过我理解 `h` 函数文档里最好加上到 [*Render Function* 这部分](https://v3.cn.vuejs.org/guide/render-function.html#%E6%B8%B2%E6%9F%93%E5%87%BD%E6%95%B0)的链接，这个需要去原文 repo 提一下。
