### ISSUE TITLE
认领未翻译：【翻译】：src/guide/migration/transition.md

### ISSUE THREAD

**Issue by huzhengen** [vuejs/docs-next-zh-cn#67]

**Comment by huzhengen** [comment]
#68

**Comment by huzhengen** [comment]
刚发现和 #61 翻译重复了。

我只粗略的看了下 Issues 列表没有 `src/guide/migration/transition.md` 就直接去翻译了，没仔细看。

**Comment by veaba** [comment]
还有一些新增加的未翻译的文档可以新翻译，不过要等#65 合并进来方可生效。

**Comment by huzhengen** [comment]
好的。

**Comment by veaba** [comment]
@huzhengen  #65 已 merge 了，现在可以发起 issue 认领。
