### ISSUE TITLE
建议字体从*斜体*的改成**加粗**

### ISSUE THREAD

**Issue by Yukon123** [vuejs/docs-next-zh-cn#672]
表示强调的时候英文可以用斜体*word*,中文*斜体*会影响观感,和旁边的字会几乎有重叠,建议改成**加粗**来表示强调.
![image](https://user-images.githubusercontent.com/82578034/130330260-9ffeee30-212c-4a62-8dd7-04e7ef5f747c.png)

**Comment by Jinjiang** [comment]
能够理解你的意思，但这个问题有点超出了我们希望讨论的范围，因为这不只是我们 Vue 中文文档的问题，是整个中文在网页中排版和渲染的问题。
我建议该议题在 W3C 中文排版规范先讨论 https://github.com/w3c/clreq 有进一步结论之后我们同步过来
谢谢支持
