### ISSUE TITLE
中文仓库是否支持algolia特性？

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#7]
有一个原仓库的特性：使用了 algolia，但仅支持英文现在。

我尝试注册了 `algolia`，发现需要还需要特别做搜索的 json 文件。

如果是这样，官方库做 i18n 就很麻烦，需要各个 i18n 库都需要制作自己的 json 文件来支持搜索。

————————————————————————————————
2020年9月20日：
由于中文库移除了 algolia 特性，再加上原英文仓库 变量有问题，这导致了中文仓库丢失了搜索功能，已给英文 [PR](https://github.com/vuejs/docs-next/pull/519) 修复该问题。

本地搜索框恢复后，将会给 algolia 提交 PR，以增加 algolia 特性。

**Comment by QC-L** [comment]
@Jinjiang 可以申请的，申请方式很简单。

**Comment by Justineo** [comment]
Algolia Docsearch 我记得直接支持配置多语言的，需要给他们的配置仓库提交一个 PR。

**Comment by QC-L** [comment]
把英文文档的配置，改个名字就可以了。具体配置会有人帮忙修改的

**Comment by Justineo** [comment]
目前 Vue 3 的配置在这里：https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs-v3.json

**Comment by veaba** [comment]
结合@Justineo 上面 [反馈的情况](https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs-v3.json) 与我自己的测试结果实现 algolia 特性 方案如下：

- 方式一：需要给[Algolia 发起 PR](https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs-v3.json) ，添加 v3 中文站的搜索配置文件，请求他们帮忙收录站点。

- 方式二：如果自己制作的话就很麻烦，需要一定的数据结构才能呈现（不建议采取这种方式。官方给定的默认demo数据结构，就是那个firstName的不行。）：
比如需要导入类似这个 json结构：

```json
{
  "type": "lvl1",
  "url": "https://v3.vuejs.org/api/options-dom.html#dom",
  "content": "Now when you run  vm.fullName = &#x27;John Doe&#x27; , the setter will be invoked and  vm.firstName  and  vm.lastName  will be updated accordingly",
  "hierarchy": {
    "lvl0": "Essentials",
    "lvl1": "Computed Properties and Watchers",
    "lvl2": "Computed Properties",
    "lvl3": "Computed Setter"
  },
  "objectID": "5671297001"
}
```
Algolia 搜索 结果：

![image](https://user-images.githubusercontent.com/8652596/92436630-b549d980-f1d7-11ea-8131-3de503401c61.png)

------------------------------------------------------------------
方式一的提前是，证书问题需要解决。

目前v3 中文站有两种方式可以访问（后续需要测试访问速度来决定采取何种部署方案）：

1. 通过 netlify 部署的：https://vue-docs-next-zh-cn.netlify.app  （国内访问比较卡，测试地：杭州）
2. 通过 `github actions`  部署的 `gh-pages`：：https://v3.cn.vuejs.org （证书原因无法访问）

之前筹备的域名 `v3.cn.vuejs.org` 现在似乎是因为 Cloudflare 证书的原因，无法访问 `gh-pages` 分支，提示如下：

> ERR_SSL_VERSION_OR_CIPHER_MISMATCH

![image](https://user-images.githubusercontent.com/8652596/92436772-0bb71800-f1d8-11ea-8004-b07ffb89bff0.png)

总结：中文仓库支持 `algolia` 特性也是可以的，速度还算不错，方法也找到了，只是需要解决域名证书的问题。

**Comment by Jinjiang** [comment]
我为我们的文档提交了独立的申请，有几点考虑：

- DocSearch 的多语言配置感觉更像是在同一个站点下的，感觉和我们目前的状态不太吻合。
- 我们 v2 的文档中英文也是分看的 https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs_cn2.json
- 中心化的多语言配置不只是中文版的问题，需要和整个文档团队商量，从目前 Vue 团队的文档和翻译工作现状来看，个人觉得比较难协作
- 从体验上看，分开申请不存在实际的体验问题

更多进展我会及时同步到这里。

**Comment by veaba** [comment]
> 我为我们的文档提交了独立的申请，有几点考虑：
> 
> * DocSearch 的多语言配置感觉更像是在同一个站点下的，感觉和我们目前的状态不太吻合。
> * 我们 v2 的文档中英文也是分看的 https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs_cn2.json
> * 中心化的多语言配置不只是中文版的问题，需要和整个文档团队商量，从目前 Vue 团队的文档和翻译工作现状来看，个人觉得比较难协作
> * 从体验上看，分开申请不存在实际的体验问题
> 
> 更多进展我会及时同步到这里。

参考前面讨论的（https://github.com/vuejs/docs-next-zh-cn/issues/7#issuecomment-688620296） ，应该可以仿照英文版 v3 的config ，可能需要一个conversation_id，为此我昨天也申请了，等批下来，看下结果。
