### ISSUE TITLE
v-if和v-for的优先级问题，v2.x和 v3发生了变化吗？

### ISSUE THREAD

**Issue by YangJ0605** [vuejs/docs-next-zh-cn#701]
v2.x   当 v-if 与 v-for 一起使用时，v-for 具有比 v-if 更高的优先级。请查阅列表渲染指南以获取详细信息。（v2.x https://cn.vuejs.org/v2/guide/conditional.html#v-if-%E4%B8%8E-v-for-%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8）

v3.x 当 v-if 与 v-for 一起使用时，v-if 具有比 v-for 更高的优先级。请查阅列表渲染指南以获取详细信息。 (https://v3.cn.vuejs.org/guide/conditional.html#v-if-%E4%B8%8E-v-for-%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8)

**Comment by Justineo** [comment]
https://v3.cn.vuejs.org/guide/migration/v-if-v-for.html
