### ISSUE TITLE
关于 guide/migration/introduction 中的视频

### ISSUE THREAD

**Issue by wxsms** [vuejs/docs-next-zh-cn#702]
https://player.vimeo.com/video/440868720

这个视频地址在中国网络下貌似被 block 了。是否有必要把它挪到中国的视频提供商下，比如b站？如果不挪，是否可以删除？

**Comment by konpeki622** [comment]
感觉这个可以问一下英文站社区的意见

**Comment by wxsms** [comment]
> 感觉这个可以问一下英文站社区的意见

我的意思是，单独处理一下中文站的视频。如果不处理的话，没有科学上网的人页面中会有一块白的。

**Comment by veaba** [comment]
@Jinjiang youku 被屏蔽了。。

**Comment by Jinjiang** [comment]
我来试着问问看

**Comment by junmer** [comment]
@Jinjiang 我在 youku，这个之前背景不太了解，我看看哦，周一反馈

**Comment by junmer** [comment]
> @Jinjiang 我在 youku，这个之前背景不太了解，我看看哦，周一反馈

@Jinjiang youku 视频屏蔽问题已联系相关同学解除，原因是广告误判，后面保持沟通 😄

**Comment by veaba** [comment]
鉴于此 issue 得到 @junmer 协助解决， 此 issue 将 close。

**Comment by wxsms** [comment]
这个问题解决了吗？貌似现在网页上的链接还是那个，也依然被 block 着。

**Comment by junmer** [comment]
@wxsms 之前解决的是首页 “WHY VUE.JS?” 弹窗中的 https://player.youku.com/embed/XMzMwMTYyODMyNA==?autoplay=true&client_id=37ae6144009e277d 。

又看了一下，您反馈这个视频地址不是首页的视频，这个是哪个页面里的呢？ 
@veaba 后面 cn 可能需要您上传，并替换一下 vimeo ～

**Comment by wxsms** [comment]
issue 标题有提到，我反馈的是 https://v3.cn.vuejs.org/guide/migration/introduction.html 中的视频。

**Comment by veaba** [comment]
两个事情：
1、迁移里面我这边看着挺正常的。
2、@junmer  帮忙解封的是 首页的。

![image](https://user-images.githubusercontent.com/8652596/133566499-ed9a17c4-a95a-4e70-b9f0-fca0befa8ab5.png)

**Comment by wxsms** [comment]
> 两个事情：
> 1、迁移里面我这边看着挺正常的。
> 2、@junmer 帮忙解封的是 首页的。
> 
> ![image](https://user-images.githubusercontent.com/8652596/133566499-ed9a17c4-a95a-4e70-b9f0-fca0befa8ab5.png)

你开了梯子吗？我这边电信网络和 4G 网络都打不开。

**Comment by veaba** [comment]
如果国内有问题，到麻烦 @jinjiang  上传到 youku。
我这边能访问  google，应该 是梯子了。

**Comment by Jinjiang** [comment]
不好意思我澄清一下，我之前私下反馈到优酷的问题是首页 Why Vue 不能打开的问题，那个是之前和优酷谈过的合作。这个问题我理解是讨论原议题的过程中顺便发现的。当然目前也借由 @junmer 的帮助解决了。

至于 guide/migration/introduction 中的视频，是另外一个新问题。我们之前和优酷的合作里只谈到了首页的视频。如果要移植这个视频到优酷或其它任意国内的视频平台，需要以下几个步骤：

1. 得到 Vue Mastery 的许可
2. 翻译成中文 (通常是加中文字幕)
3. 得到国内视频平台的赞助或合作许可
4. 上传并替换掉英文站的视频源，必要的时候需要改动 JS 代码

考虑到这个步骤的复杂性，我倾向于分开两件事来处理：

1. 如果网页因嵌入 vimeo 脚本此而被阻塞或加载缓慢，建议先把嵌入式的视频及其相关三方脚本去掉，换为一个简单的 vimeo 外部链接，这样保证内容的基本可访问性 (当然可能需要翻墙，但至少符合用户正常的预期)，同时网页内容可以正常打开并被浏览
2. 与此同时寻求商务合作并完成相应的翻译和编码等流程

第一件事我们现在就可以做，第二件事如果值得继续推进的话，我这边先和 Vue Mastery 申请授权，然后我们再视频制作 + 联系外部协作。届时不知 @junmer 是否还可以帮忙协调和优酷的合作。但目前我们还没走到这一步。

以上是我了解到的情况和我个人的建议。当然我同时也希望得到大家更多的想法和建议。

谢谢

**Comment by wxsms** [comment]
> 如果网页因嵌入 vimeo 脚本此而被阻塞或加载缓慢，建议先把嵌入式的视频及其相关三方脚本去掉，换为一个简单的 vimeo 外部链接，这样保证内容的基本可访问性 (当然可能需要翻墙，但至少符合用户正常的预期)，同时网页内容可以正常打开并被浏览

这个方案我赞同，先简单处理一下避免页面中出现空白。目前是嵌入了 iframe。

**Comment by Jinjiang** [comment]
鉴于该视频已经在新版文档中被移除了，所以关闭该 issue。谢谢
