### ISSUE TITLE
src/guide/component-slots.md 文件中所有的span标签都没有闭合

### ISSUE THREAD

**Issue by happyhuizai** [vuejs/docs-next-zh-cn#74]
![20200919193141 2](https://user-images.githubusercontent.com/29218617/93666228-fd59dd80-faae-11ea-872e-90cfb0261bfc.jpg)

**Comment by veaba** [comment]
@happyhuizai 你好，非常感谢指出该问题，如果可以的话，可以参考置顶 issue 指南，发起 PR，参与本仓库的贡献。

我认为，如果你能够发起 PR， 这会使得这个 issue 非常有意义！ 

如果你愿意的话，我会保留这个 “小问题” 一定时间，等你发起 PR，一起修复该问题。

**Comment by ajycc20** [comment]
> @happyhuizai 你好，非常感谢指出该问题，如果可以的话，可以参考置顶 issue 指南，发起 PR，参与本仓库的贡献。
> 
> 我认为，如果你能够发起 PR， 这会使得这个 issue 非常有意义！
> 
> 如果你愿意的话，我会保留这个 “小问题” 一定时间，等你发起 PR，一起修复该问题。

... 顺手提交了，尴尬

**Comment by veaba** [comment]
> > @happyhuizai 你好，非常感谢指出该问题，如果可以的话，可以参考置顶 issue 指南，发起 PR，参与本仓库的贡献。
> > 我认为，如果你能够发起 PR， 这会使得这个 issue 非常有意义！
> > 如果你愿意的话，我会保留这个 “小问题” 一定时间，等你发起 PR，一起修复该问题。
> 
> ... 顺手提交了，尴尬

我还没说完。。你手速有点快了吧。可以稍微保留一下 PR 位置给  @happyhuizai 吗？

**Comment by ajycc20** [comment]
> > > @happyhuizai 你好，非常感谢指出该问题，如果可以的话，可以参考置顶 issue 指南，发起 PR，参与本仓库的贡献。
> > > 我认为，如果你能够发起 PR， 这会使得这个 issue 非常有意义！
> > > 如果你愿意的话，我会保留这个 “小问题” 一定时间，等你发起 PR，一起修复该问题。
> > 
> > 
> > ... 顺手提交了，尴尬
> 
> 我还没说完。。你手速有点快了吧。可以稍微保留一下 PR 位置给 @happyhuizai 吗？

哈哈，取消了
