### ISSUE TITLE
开启生产环境模式

### ISSUE THREAD

**Issue by greenHandOnWeb** [vuejs/docs-next-zh-cn#742]
[在开发期间，Vue 提供了许多警告，以帮助你处理常见的错误和隐患。但是，这些警告字符串在生产环境中会变得无意义，并且会增大应用程序的负担。此外，有些警告检查的运行时成本很小，可以在生产环境模式中避免。](url:https://v3.cn.vuejs.org/guide/tooling/deployment.html#%E5%BC%80%E5%90%AF%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E6%A8%A1%E5%BC%8F)

其中：有些警告检查的运行时成本很小，可以在生产环境模式中避免。

感觉逻辑不正确：运行成本很小，避免和不避免应该相差不大。
应该是  运行成本很大，才需要在生产环境模式中避免。

不知道自己的想法对不对，希望检查核实是否是翻译有误或文档错误。

**Comment by Jinjiang** [comment]
@greenHandOnWeb 不介意的话可以直接在英文原站开 issue 更广泛地讨论这个问题，我们这边仅从英文站做同步。谢谢

**Comment by Cnotech** [comment]
我认为这可能是一处模棱两可的翻译，[英文版](https://v3.vuejs.org/guide/tooling/deployment.html)对应的内容如下：

> In addition, some of these warning checks have small runtime costs that can be avoided in [production mode](https://cli.vuejs.org/guide/mode-and-env.html#modes).

我建议的翻译如下：此外，有一些警告检查还会产生些许的运行时开销，在[生产模式](https://cli.vuejs.org/zh/guide/mode-and-env.html#模式)下是可以回避这些开销的。

**Comment by Justineo** [comment]
重点在“有”并不在“小”，所以能避免自然是好的。你修改过的翻译我觉得不错，欢迎发PR 👍

**Comment by greenHandOnWeb** [comment]
同意，谢谢！

**Comment by greenHandOnWeb** [comment]
> @greenHandOnWeb 不介意的话可以直接在英文原站开 issue 更广泛地讨论这个问题，我们这边仅从英文站做同步。谢谢

不好意思，之前没有看到。
我还有一个疑问：所以，Vue官方文档原文是用 英文 写的，中文只是翻译版本?

**Comment by Cnotech** [comment]
是这样的，详情可见尤雨溪在知乎的回答：为什么 Vue 的更新记录没有中文，中文文档也一直滞后？ - 尤雨溪的回答 - 知乎
https://www.zhihu.com/question/49884331/answer/118492169

**Comment by greenHandOnWeb** [comment]
# #

> 是这样的，详情可见尤雨溪在知乎的回答：为什么 Vue 的更新记录没有中文，中文文档也一直滞后？ - 尤雨溪的回答 - 知乎
> https://www.zhihu.com/question/49884331/answer/118492169

@Cnotech 好的，谢谢你！

**Comment by Jinjiang** [comment]
> > @greenHandOnWeb 不介意的话可以直接在英文原站开 issue 更广泛地讨论这个问题，我们这边仅从英文站做同步。谢谢
> 
> @Jinjiang 不好意思，之前没有留意。
> 我还有一个疑问：所以，Vue官方文档原文是用 英文 写的，中文只是翻译版本?

是的，中文版只是英文版的翻译，英文版是原版，具体工作和参与方式可以顺着 README 进行查阅
