### ISSUE TITLE
vue3.2.12版本defineExpose返回的数组会被深度reactive化（数组内部的对象会变成proxy）

### ISSUE THREAD

**Issue by steiner001** [vuejs/docs-next-zh-cn#750]
子组件
import {ref} from ‘vue’
const a=ref([{b:1,c:{d:2}}])
defineExpose({a})
父组件
import { ref } from “vue”
import A from “./a.vue”
const aref = ref()
const see = () => {
console.log(“aref: “, aref.value.a)
console.log(“aref: “, aref.value.a[0])
}
![1632405232](https://user-images.githubusercontent.com/39907423/134519919-a776fb07-3ed7-4102-b5d0-194f8e90b22d.png)

这样格式无法传参给后端，请问大家，有没有方法讲深度 reactive 化的对象或者数组转化为普通的对象？

**Comment by veaba** [comment]
see https://v3.cn.vuejs.org/api/refs-api.html#torefs

或者  JSON.parse(JSON.stringify)。

我理解上，发起请求时，应该是自动移除那些多余的属性，可以尝试一下。

鉴于此 issue 无关文档内容，这里将 close。
