### ISSUE TITLE
关于是否统一迁移符号到加粗符号外讨论

### ISSUE THREAD

**Issue by veaba** [vuejs/docs-next-zh-cn#78]
该讨论来自#49 ，现独立出来发起 issue 讨论

@Jinjiang ：

> 标点符号写在星号里面似乎不影响解析和渲染，这种情况下我们是否需要刻意并统一把标点符号移到外部?

仅当加粗 `**...**` 右侧有汉字时候，需要迁移到加粗符号 `**`外面，但如果加粗符号 `**` 外无汉字，也是可以渲染的。

demo：

```
- **你好，**世界   // 失败
- **你好，** 世界  // 成功
- **你好**，世界   // 成功
```

![](https://user-images.githubusercontent.com/8652596/93082504-9fe71a80-f6c3-11ea-9cfe-4719c3934116.png)

@Jinjiang @Justineo 

目前有三种方法可选：

1. 加粗 `**` 最后一个符号，一律移到它的右侧，如：
  -  `**你好，**世界` ==> `**你好**，世界`
  -`**你好，世界。**` ==> `**你好，世界**`。
2. 最后一个 `**` 右侧如有汉字可空格，否则原样，如：
  - `**你好，**世界` ==> `**你好，** 世界`
  - `**你好，**世界` ==> `**你好，**世界`
3. 如果 `**` 最后一个符号存在且右侧存在汉字时，符号迁移到右侧，否则可保留原版，否则，如：
  - `**该钩子在服务器端渲染期间不被调用。**` 世界  ==>`**该钩子在服务器端渲染期间不被调用**`。 世界
  - `**该钩子在服务器端渲染期间不被调用。**` ==>`**该钩子在服务器端渲染期间不被调用。**`

**Comment by ajycc20** [comment]
是不是方法1更为统一一点，个人感觉加粗对于标点的影响并不大

**Comment by zhenzhenChange** [comment]
关于符号的问题，我也想说一个，请看以下示例：
就是 code 标记 `` 的问题：

书写格式：
![w7phfs.png](https://s1.ax1x.com/2020/09/20/w7phfs.png)

我们来看一个`case`，渲染后我们双击选中

![w7pGy6.png](https://s1.ax1x.com/2020/09/20/w7pGy6.png)

再来看第二个 `case` 吧，渲染后双击选中

![w7pyOf.png](https://s1.ax1x.com/2020/09/20/w7pyOf.png)

第一个示例，标记左右都没有空格，双击选中之后自然而然就是【case】单词
第二个示例，标记左右都有空格，双击选中之后【case】的右边多了一个空格

诚然，根据一些书写规范，英文单词在中文之间建议在英文左右添加空格，以此保证可读性

但在 code 标记中，渲染出来的效果，左右已经有足够的空隙了

另外，我觉得有些开发者（包括我）习惯双击关键字，然后复制搜索或者用于其他地方，多了个空格造成了一丢丢困扰

当然，这一丢丢影响不算什么，这只是根据我个人的体验而提出的小问题

所以，我提议，在使用 code 标记时：

- 若标记左边是字母（包括数字），则加上空格（这其实是保持英文单词左右加上空格的书写规范）
- 标记左右遇到标点符号，无须加空格
- 标记左右都是中文，无须加空格

**Comment by veaba** [comment]
上面讨论是一个有趣的体验改进，虽然与加粗符号的讨论不是一个专注的话题，但也是增强阅读、交互体验本身的内容，可以持续探讨。

刚才尝试改动为：仅标记左边空格，右边不空格，双击复制似乎没什么问题，但看起来很不协调。

**Comment by zhenzhenChange** [comment]
是的，仅左边加，而右边不加，首先在书写上不协调，然后实际效果上其实是左边宽了一些（标记本身的间距以及加上了一个空格）
 （要不辛苦您 @veaba  单独开一个issue吧，刚刚因为这个问题，有点同属于符号，就没多想

**Comment by zhenzhenChange** [comment]
@veaba 没问题，你们先走流程

**Comment by Jinjiang** [comment]
关于 code 标记，我能理解几位的意见和目前网站呈现出来的现状。

我相信类似的细节体验在我们的文档中甚至所有你在互联网能看得到的文档中还大量存在，我们确定翻译规范，一方面是权衡各方面利弊，另一方面是要保持一个可以长期有确定性的规范，同时在不产生关键问题和歧义的基础上尊重先入为主的观点。不然很容易在没有绝对对错的地方陷入无休止的讨论。希望大家能够理解这一点。🙏

综上所述，我觉得这里没有特别需要修改的必要。

另外这个议题其实和这个 issue 的标题有一些距离，如果大家仍觉得需要更多讨论，我建议单开一个 issue，不然大家会因为这个标题错过自己可能感兴趣的讨论或提供帮助的机会。

**Comment by Jinjiang** [comment]
关于加粗符号 (或强调符号)，我的看法是在 markdown 解析出现问题的情况下再调整标点符号的位置。因为：

- 由于 markdown 本身语法的关系，这里要么是渲染不正确，要么是对原文产生了细微的调整 (即便是少强调了一个标点符号)。两者都应该尽量避免。
- 而且为了统一格式把整句话留一个标点符号在星号外面确实很奇怪，一定会引发更多的讨论和争议。

相同的留言在这里 https://github.com/vuejs/docs-next-zh-cn/pull/49#discussion_r491719256

**Comment by veaba** [comment]
@Jinjiang @Justineo 
经过#78，以及#49 的讨论结果，现将 issue #78 讨论的结果调整如下：
已更新到 [关于加粗和斜体格式的约定 wiki](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E5%85%B3%E4%BA%8E%E5%8A%A0%E7%B2%97%E5%92%8C%E6%96%9C%E4%BD%93%E6%A0%BC%E5%BC%8F%E7%9A%84%E7%BA%A6%E5%AE%9A)。

- 在加粗段落，仅当影响 markdown 渲染情况下，将最后一个句号或逗号、冒号，迁移到 ** 右侧。(讨论：#49、#78）

```
// 情况1：
 **相对胜于晦涩。**例如，一个 `<BlogPost>` 组件例子比 `<CurrencyExchangeSettings>` 更好。 // vuepress 无法渲染
（调整为：）
**相对胜于晦涩**。例如，一个 `<BlogPost>` 组件例子比 `<CurrencyExchangeSettings>` 更好。  // 迁移句号有加粗符号右侧

// 情况2：
**你好，**世界 ==> **你好**，世界 (句号迁移到右侧)
（调整为：）
**你好，世界。** ==> **你好，世界。** (不影响渲染，保持原样)
```
