### ISSUE TITLE
Caveats 如何翻译的问题

### ISSUE THREAD

**Issue by wxsms** [vuejs/docs-next-zh-cn#793]
目前我发现的是很多地方翻译为了“警告”，但是这很难理解。比如“Externals Caveats”->“关于外部依赖的警告”，“Hydration Caveats” -> “Hydration 警告”。有点让人摸不着头脑。实际上想表达的意思应该是“需要注意的地方”。

目前我发现的是 v2 文档有些地方将它翻译为了“坑”，比如“Hydration Caveats” -> “一些需要注意的坑”，这个就好理解很多。希望可以得出一个结论，并把它添加到 wiki 中。

**Comment by veaba** [comment]
召唤一下 @Jinjiang @Justineo 。

本人对于 hydration 的理解不深，对此，我就不发表看法了。

**Comment by Justineo** [comment]
“坑”的意思挺合适但是表达其实不太书面。感觉可以翻译成“注意事项”？

**Comment by wxsms** [comment]
> “坑”的意思挺合适但是表达其实不太书面。感觉可以翻译成“注意事项”？

“注意事项”还不错。“Externals Caveats”->“关于外部依赖的注意事项”，“Hydration Caveats” -> “关于 Hydration 的注意事项”。

**Comment by wxsms** [comment]
题外话：我觉得 hydration 这个词可以 follow v2 翻译成“激活”。https://github.com/vuejs/docs-next-zh-cn/pull/786

**Comment by Jinjiang** [comment]
注意事项 +1

**Comment by veaba** [comment]
我注意到该 issue 已得到处理，现在 close 。
感谢讨论

**Comment by Jinjiang** [comment]
我追加了一个 PR #812 
谢谢
