### ISSUE TITLE
认领【已翻译未校对】：src/api/global-api.md

### ISSUE THREAD

**Issue by zhenzhenChange** [vuejs/docs-next-zh-cn#80]

**Comment by zhenzhenChange** [comment]
@veaba 好哥哥，你似乎看错啦，我领的是src/api/global-api.md，不是src/guide/mitration/global-api.md 哈哈

**Comment by veaba** [comment]
已调整。

**Comment by zhenzhenChange** [comment]
PS：该文档无法使用 zhlint 工具校验

**Comment by Jinjiang** [comment]
@zhenzhenChange zhlint 的问题我会单独看一下，可能需要一些时间，这里可以先跳过工具校验的部分。🙏
