### ISSUE TITLE
When I use Jump to the main content link function + vue - while on a router cannot jump to the main content

### ISSUE THREAD

**Issue by lilangtop** [vuejs/docs-next-zh-cn#807]
For example in my current position
127.0.0.1: # 3000 / / home
Click on the links to jump to the main content
<a href="#main" > jump to the main content</a>
At this time not to jump to the location of the element id as the "main", the address bar's url voice change
Became so
192.168.0.1: / # 3000 / main
Excuse me, I should how to ensure that each click to jump to the main content link to be able to make ID a "main" elements of the right focus
Thank you
I wish
A happy life!

**Comment by wxsms** [comment]
Hello there! This project is for Chinese document translation, please do not raise issues related to Vue.js usage here. Thank you!
