### ISSUE TITLE
bug: 在vue3的组件中，父组件给子组件传入一个router-link的to的路径 ，子组件读取不到

### ISSUE THREAD

**Issue by yuehan2020** [vuejs/docs-next-zh-cn#811]
`<Car title="小涵音乐" banner="https://z3.ax1x.com/2021/11/16/IfDVvd.png" ToGo="/backstage" ></Car>`          
父组件

子组件 
         `  <router-link :to="ToGo">点击进入</router-link>`         

会弹出Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next

**Comment by wxsms** [comment]
> Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next

请在这个链接发起 issue。谢谢。
