### ISSUE TITLE
bug: [文档]渲染函数-创建组件-vnode可能错误

### ISSUE THREAD

**Issue by fjlJENNY** [vuejs/docs-next-zh-cn#825]
<img width="1469" alt="企业微信截图_a68c16e7-e501-47d5-90e2-465dfdff65b6" src="https://user-images.githubusercontent.com/13270748/143839363-d498ac1a-6f6c-42a8-b062-c02375ecdd3d.png">

**Comment by wxsms** [comment]
此处英文版原文也是如此，而且看起来并没有错误，不知道你的疑问点在哪里？如果对文档内容有疑问，可以到英文版提issue，这边会定期同步。
