### ISSUE TITLE
bug: 修改响应式 property 的代码示例错误使用this

### ISSUE THREAD

**Issue by lizheng0515** [vuejs/docs-next-zh-cn#830]
https://v3.cn.vuejs.org/guide/composition-api-provide-inject.html#%E4%BF%AE%E6%94%B9%E5%93%8D%E5%BA%94%E5%BC%8F-property

文档中介绍 **修改响应式 property** 的**代码示例**里,
 `methods `里面定义了一个`updateLocation`方法，
 里面用`this`来访问`location `

我在"vue": "^3.2.16",版本工程里尝试，发现vscode提示无法访问`location`
这里应该不能用this来访问location吧，**methods 对象的 this指向data返回的对象**。

![image](https://user-images.githubusercontent.com/25120505/144421922-85f1472e-ea80-4800-b0fa-4771c7745df7.png)

```js
<!-- src/components/MyMap.vue -->
<template>
  <MyMarker />
</template>

<script>
import { provide, reactive, ref } from 'vue'
import MyMarker from './MyMarker.vue'

export default {
  components: {
    MyMarker
  },
  setup() {
    const location = ref('North Pole')
    const geolocation = reactive({
      longitude: 90,
      latitude: 135
    })

    provide('location', location)
    provide('geolocation', geolocation)

    return {
      location
    }
  },
  methods: {
    updateLocation() {
      this.location = 'South Pole'
    }
  }
}
</script>
```

```js
// 当 methods 有方法时
if (methods) {
    // 对methods对象中的每一个方法遍历
    for (const key in methods) {
        // 取出每一个方法
      const methodHandler = (methods as MethodOptions)[key]
        // 判断是否是方法Function类型
      if (isFunction(methodHandler)) {
        // In dev mode, we use the `createRenderContext` function to define
        // methods to the proxy target, and those are read-only but
        // reconfigurable, so it needs to be redefined here
        // 在开发环境时
        if (__DEV__) {
          Object.defineProperty(ctx, key, {
            // 对每个方法进行绑定this的作用域 this等于这里的publicThis
            value: methodHandler.bind(publicThis),
            configurable: true,
            enumerable: true,
            writable: true
          })
        } else {
            // 非开发环境时，对每个方法进行this的绑定
          ctx[key] = methodHandler.bind(publicThis)
        }
        if (__DEV__) {
          checkDuplicateProperties!(OptionTypes.METHODS, key)
        }
      } else if (__DEV__) {
        warn(
          `Method "${key}" has type "${typeof methodHandler}" in the component definition. ` +
            `Did you reference the function correctly?`
        )
      }
    }
  }

```
publicThis的指向是 实例的代理

`const publicThis = instance.proxy! as any
`
而这个实例的代理就是Vue中的data对象，所以this指向的应该是data返回的对象

希望能获得解答！！！

**Comment by wxsms** [comment]
麻烦贴一下你认为有问题的文档链接或者截图？你上面给的链接是链接到项目wiki的，我并不是很明白你说的是哪一个位置的示例代码有问题。

**Comment by lizheng0515** [comment]
> 麻烦贴一下你认为有问题的文档链接或者截图？你上面给的链接是链接到项目wiki的，我并不是很明白你说的是哪一个位置的示例代码有问题。

更改了链接。
![image](https://user-images.githubusercontent.com/25120505/144610294-d2c787e4-87c6-46cc-908f-b52b02ad59eb.png)

**Comment by lizheng0515** [comment]
英文版也是错的
![image](https://user-images.githubusercontent.com/25120505/144687517-039a5345-ac6e-4bcf-8675-07f5dfcf4247.png)

**Comment by wxsms** [comment]
[https://sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICB7e2xvY2F0aW9ufX1cbiAgPGJ1dHRvbiB0eXBlPVwiYnV0dG9uXCIgQGNsaWNrPVwidXBkYXRlTG9jYXRpb25cIj5cbiAgICB1cGRhdGVMb2NhdGlvblxuICA8L2J1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5pbXBvcnQgeyBwcm92aWRlLCByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIHNldHVwKCkge1xuICAgIGNvbnN0IGxvY2F0aW9uID0gcmVmKCdOb3J0aCBQb2xlJylcbiAgICBjb25zdCBnZW9sb2NhdGlvbiA9IHJlYWN0aXZlKHtcbiAgICAgIGxvbmdpdHVkZTogOTAsXG4gICAgICBsYXRpdHVkZTogMTM1XG4gICAgfSlcblxuICAgIHJldHVybiB7XG4gICAgICBsb2NhdGlvblxuICAgIH1cbiAgfSxcbiAgbWV0aG9kczoge1xuICAgIHVwZGF0ZUxvY2F0aW9uKCkge1xuICAgICAgY29uc29sZS5sb2codGhpcy5sb2NhdGlvbilcbiAgICAgIHRoaXMubG9jYXRpb24gPSAnU291dGggUG9sZSdcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==)

这个用法并没有问题，请见demo链接。至于vscode的提示问题不在本仓库讨论范畴，请移步至合适的项目提问。谢谢！
