### ISSUE TITLE
sleight-of-hand 是否翻译为 “微调” 比较合适呢？

### ISSUE THREAD

**Issue by maogongzi** [vuejs/docs-next-zh-cn#842]
您好，我在对比文档: [`src/guide/transitions-enterleave.md`](https://github.com/vuejs/docs-next-zh-cn/blob/master/src/guide/transitions-enterleave.md) 时，发现原文  **sleight-of-hand** 翻译为 **轻描淡写** 有一些不太好理解，可否调整为诸如 **微调** 之类呢？

> We can use this to coordinate more expressive movement, such as a folding card, as demonstrated below. It's actually two elements transitioning between each other, but since the beginning and end states are scaling the same: horizontally to 0, it appears like one fluid movement. This type of sleight-of-hand can be very useful for realistic UI microinteractions:

> 我们可以用它来协调更具表现力的动作，例如折叠卡片，如下所示。这实际上是两个元素在彼此之间转换，但是由于开始状态和结束状态的比例是相同的：水平为0，它看起来就像一个流体运动。这种轻描淡写对于真实的 UI 微交互非常有用：

我同时参照了一下日文的翻译（我不会日语，是用的谷歌翻译），显示日文中翻译为 **微调**

![Screen Shot 2021-12-14 at 16 54 06](https://user-images.githubusercontent.com/1438835/145966250-abd9063b-347c-44af-992d-ec447a4620e7.png)

**Comment by wxsms** [comment]
这个”轻描淡写“确实有待商榷。根据[牛津词典](https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/sleight-of-hand)的表述，我觉得这里应该翻译为”技巧“或”小技巧“。

> 这种技巧对于真实的 UI 微交互非常有用

不知道大家怎么看？

**Comment by Justineo** [comment]
> 这种手法/技巧对于实现拟真的 UI 微交互非常有用。
