### ISSUE TITLE
关于transition动画里的文档错误

### ISSUE THREAD

**Issue by likecreep** [vuejs/docs-next-zh-cn#858]
文档[CSS动画](https://v3.cn.vuejs.org/guide/transitions-enterleave.html#css-%E5%8A%A8%E7%94%BB)小节有如下内容：
> CSS 动画用法同 CSS 过渡，区别是在动画中 `v-enter-from` 类在节点插入 DOM 后不会立即移除，而是在 `animationend` 事件触发时移除。

经测试文档下的示例代码，观察元素可知，动画中 `v-enter-from` 类在节点插入 DOM 后也会立即移除，并不会等待`animationend` 事件触发时移除。

**Comment by wxsms** [comment]
确实 v-enter-from 并没有保留到 animationend。感觉是原文出了问题。不知道你是否方便到 [英文仓库](https://github.com/vuejs/docs) 发起一个 issue，我也可以代劳。中文版会同步来自英文版的改动。

**Comment by likecreep** [comment]
> 确实 v-enter-from 并没有保留到 animationend。感觉是原文出了问题。不知道你是否方便到 [英文仓库](https://github.com/vuejs/docs) 发起一个 issue，我也可以代劳。中文版会同步来自英文版的改动。

英文不太好避免表述有误，麻烦代发一下吧。
