### ISSUE TITLE
bug: 中文文档中自定义指令描述错误！

### ISSUE THREAD

**Issue by rinbowLi** [vuejs/docs-next-zh-cn#860]
![image](https://user-images.githubusercontent.com/38241103/148962556-7d4a1299-f1f2-4a74-bcc1-7c97fd11f0c4.png)
这个是中文文档的描述 
[截图所在地址](https://v3.cn.vuejs.org/guide/custom-directive.html)
```
<script>
import { ref, onMounted,onBeforeMount } from "vue";
export default {
  directives: {
    focus: {
      beforeMount() {
        console.log("自定义指令的beforeMount");
      },
      mounted(el) {
        console.log("自定义指令的mounted");
        el.focus();
      },
    },
  },
  setup() {
    const inputValue = ref("123");


    onBeforeMount(() => {
      console.log("组件的onBeforeMount");
    });

    onMounted(() => {
      console.log("组件的onMounted");
    });


    return () => (
      <div>
        <h2>{inputValue.value}</h2>
        <input v-model={inputValue.value} v-focus />
      </div>
    );
  },
};
</script>
```
上面是测试代码
![image](https://user-images.githubusercontent.com/38241103/148963197-30336916-00e2-4a39-875d-fdf6d2509ac6.png)
这个是打印结果，很明显自定义指令的mounted比组件的onMounted声明周期更早，所以文档中描述错误

**Comment by wxsms** [comment]
这里的英文原文是 called when the bound element's parent component is mounted，翻译过来应该就是“父组件挂载后调用”。感觉是原文出了问题。不知道你是否方便到 [英文仓库](https://github.com/vuejs/docs) 发起一个 issue，如果不方便我也可以代劳。中文版会同步来自英文版的改动。

**Comment by rinbowLi** [comment]
> 这里的英文原文是 called when the bound element's parent component is mounted，翻译过来应该就是“父组件挂载后调用”。感觉是原文出了问题。不知道你是否方便到 [英文仓库](https://github.com/vuejs/docs) 发起一个 issue，我也可以代劳。中文版会同步来自英文版的改动。

好的，我去英文仓库发个issue

**Comment by rinbowLi** [comment]
> 这里的英文原文是 called when the bound element's parent component is mounted，翻译过来应该就是“父组件挂载后调用”。感觉是原文出了问题。不知道你是否方便到 [英文仓库](https://github.com/vuejs/docs) 发起一个 issue，我也可以代劳。中文版会同步来自英文版的改动。

已经去英文仓库提了pr和issue，也通过了，中文版的什么时候可以同步上线呀

**Comment by Jinjiang** [comment]
感谢贡献，如 README 上的介绍，我们会定义从英文版做定期同步，下次同步的时候应该就会带上了
再次谢谢，不介意的话这个 issue 我先关掉了
