### ISSUE TITLE
有没有完整示例代码?

### ISSUE THREAD

**Issue by Gsonovb** [vuejs/docs-next-zh-cn#865]
有没有完整示例代码？
比如 演示组件， 包含 属性，  内部变量， 事件， 等 常见模板

最近在自学，但项关注SFC的时候，  很多组件定义都是脚本， 文件定义示例很少，而且提示不明显。

**Comment by initdc** [comment]
https://v3.cn.vuejs.org/guide/introduction.html

https://codepen.io/team/Vue/pens/public
