### ISSUE TITLE
v3文档翻译有误

### ISSUE THREAD

**Issue by DOVE-PH** [vuejs/docs-next-zh-cn#87]
[链接地址](https://v3.cn.vuejs.org/guide/composition-api-setup.html#%E4%B8%8A%E4%B8%8B%E6%96%87)
如上链接，中的MyBook.vue示例代码中注释。
`// Attribute (响应式 object)` 和`// Slots (响应式 object)` 应该译为非响应式object

**Comment by veaba** [comment]
已在PR #90 中修复该问题，感谢反馈，现将 close 该 issue。
