### ISSUE TITLE
该版本文档停止更新，欢迎去新版文档贡献

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/docs-next-zh-cn#886]
如题。由于英文版文档重新撰写了新版本，所以中文版也会做相应的跟进，同时新版文档的仓库会放在一个新的 GitHub org 下。具体的仓库地址是：

https://github.com/vuejs-translations/docs-zh-cn/

在新版文档翻译和校对完成之前，我们仍然会在中文官网部署目前的这个版本，该仓库仅会修复一些错别字和译法改进，不会保持和英文版的同步。

新版文档翻译和校对完毕之后，该仓库会做归档处理并停止维护。

感谢大家的理解和支持

**Comment by liyuhang1997** [comment]
是否有点混乱
[vuejs-translations/docs-zh-cn: Vue 文档官方中文翻译 ｜ Official Chinese translation for Vue docs](https://github.com/vuejs-translations/docs-zh-cn)

[vuejs/docs-next-zh-cn: Chinese translation for v3.vuejs.org](https://github.com/vuejs/docs-next-zh-cn)

**Comment by Jinjiang** [comment]
新版网站已经正式上线，该仓库稍后会做归档处理，该 issue 关闭。谢谢
