### ISSUE TITLE
v3文档翻译有误

### ISSUE THREAD

**Issue by chenkai0520** [vuejs/docs-next-zh-cn#95]
[v3.cn.vuejs.org 全局-api](https://v3.cn.vuejs.org/guide/migration/global-api.html#%E5%85%A8%E5%B1%80-api)

![截屏2020-09-21 上午11 03 36](https://user-images.githubusercontent.com/30174970/93730193-220e9c00-fbfa-11ea-8b09-2a3e10d31131.png)

`Vue.使用` 应该为`Vue.use`

**Comment by veaba** [comment]
@chenkai0520  你好，非常感谢指出该问题，如果可以的话，可以参考置顶 issue 指南，发起 PR，参与本仓库的贡献。如果你能够发起 PR， 修复该问题，这会使得这个 issue 非常有意义！
