### ISSUE TITLE
使用 zhlint 检查文件时出现错误

### ISSUE THREAD

**Issue by zhenzhenChange** [vuejs/docs-next-zh-cn#96]
如图所示，在校验 src/api/global-api.md 时出现错误：

![wHJc5D.png](https://s1.ax1x.com/2020/09/21/wHJc5D.png)

我也试过校验其他几个文件（文件名有 - 的，或者只有一个单词的）都能校验成功QAQ：

![wHYlJe.png](https://s1.ax1x.com/2020/09/21/wHYlJe.png)

**Comment by veaba** [comment]
可以给 [Jinjiang/zhlint](https://github.com/Jinjiang/zhlint) ，提交相关 issue，目前存在以下问题：
1. 双重 `((` 符号也会出现错误
2. 对符号 `:::` 也有反馈错误提示

建议你参考 [术语翻译约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A) 实际情况手动调整。

该问题实际是 `zhlint` 的相关，现将 close issue.
